-- CreateTable
CREATE TABLE `OPDAssessment` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `doctorId` INTEGER NULL,
    `appointmentId` INTEGER NULL,
    `name` VARCHAR(191) NULL,
    `age` VARCHAR(191) NULL,
    `gender` VARCHAR(191) NULL,
    `uhId` VARCHAR(191) NULL,
    `height` VARCHAR(191) NULL,
    `weight` VARCHAR(191) NULL,
    `date` VARCHAR(191) NULL,
    `consultant` VARCHAR(191) NULL,
    `department` VARCHAR(191) NULL,
    `assessmentTime` VARCHAR(191) NULL,
    `hr` VARCHAR(191) NULL,
    `rr` VARCHAR(191) NULL,
    `pulse` VARCHAR(191) NULL,
    `bp` VARCHAR(191) NULL,
    `temp` VARCHAR(191) NULL,
    `spo2` VARCHAR(191) NULL,
    `oralDiet` VARCHAR(191) NULL,
    `enteralFeed` VARCHAR(191) NULL,
    `npo` TEXT NULL,
    `specify` TEXT NULL,
    `allergies` TEXT NULL,
    `painScore` VARCHAR(191) NULL,
    `screeningReq` VARCHAR(191) NULL,
    `implantCounsel` VARCHAR(191) NULL,
    `history` TEXT NULL,
    `examination` TEXT NULL,
    `investigation` TEXT NULL,
    `treatmentPlan` TEXT NULL,
    `doctorSealSign` TEXT NULL,
    `staffName` VARCHAR(191) NULL,
    `staffEmpId` VARCHAR(191) NULL,
    `staffDateTime` DATETIME(3) NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `ERAssessment` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `doctorId` INTEGER NULL,
    `appointmentId` INTEGER NULL,
    `name` TEXT NULL,
    `age` TEXT NULL,
    `sex` TEXT NULL,
    `uhId` TEXT NULL,
    `date` TEXT NULL,
    `time` TEXT NULL,
    `pr` TEXT NULL,
    `bp` TEXT NULL,
    `rr` TEXT NULL,
    `spo2` TEXT NULL,
    `temp` TEXT NULL,
    `grbs` TEXT NULL,
    `mlcNo` TEXT NULL,
    `presentingComplaints` TEXT NULL,
    `pastHistory` TEXT NULL,
    `regularMedications` TEXT NULL,
    `abcdeAssessment` TEXT NULL,
    `examination` TEXT NULL,
    `investigation` TEXT NULL,
    `procedureDone` TEXT NULL,
    `provisionalDiagnosis` TEXT NULL,
    `treatmentAdministered` TEXT NULL,
    `referralDepartment` TEXT NULL,
    `disposition` TEXT NULL,
    `dischargePR` TEXT NULL,
    `dischargeBP` TEXT NULL,
    `dischargeRR` TEXT NULL,
    `dischargeSpo2` TEXT NULL,
    `dischargeTemp` TEXT NULL,
    `prescribedDrugs` JSON NULL,
    `otherInstructions` TEXT NULL,
    `followUp` VARCHAR(191) NULL,
    `doctorSpecialty` TEXT NULL,
    `doctorSign` TEXT NULL,
    `doctorName` VARCHAR(191) NULL,
    `kmcNo` VARCHAR(191) NULL,
    `signDateTime` DATETIME(3) NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
