-- AlterTable
ALTER TABLE `IpdPrescription` ADD COLUMN `prescriptionType` VARCHAR(191) NULL,
    ADD COLUMN `reconciledAt` DATETIME(3) NULL,
    ADD COLUMN `reconciledBy` VARCHAR(191) NULL,
    ADD COLUMN `reconciledById` INTEGER NULL,
    ADD COLUMN `reconciliationAction` VARCHAR(191) NULL,
    ADD COLUMN `reconciliationReason` TEXT NULL;

-- CreateTable
CREATE TABLE `IpdHandover` (
    `id` VARCHAR(191) NOT NULL,
    `admissionId` VARCHAR(191) NOT NULL,
    `chartDate` DATETIME(3) NOT NULL,
    `shift` VARCHAR(191) NOT NULL,
    `postOpDay` INTEGER NULL,
    `diet` TEXT NULL,
    `ventilation` TEXT NULL,
    `invasiveLines` LONGTEXT NULL,
    `infusionsTransfusions` LONGTEXT NULL,
    `puProphylaxis` TEXT NULL,
    `dvtProphylaxis` TEXT NULL,
    `painScale` INTEGER NULL,
    `gcsLoc` TEXT NULL,
    `skinIntegrity` TEXT NULL,
    `restraints` VARCHAR(191) NULL,
    `fallRisk` VARCHAR(191) NULL,
    `adl` TEXT NULL,
    `ambulation` TEXT NULL,
    `criticalLabValues` LONGTEXT NULL,
    `currentProblems` LONGTEXT NULL,
    `investigationsOrdered` LONGTEXT NULL,
    `reportsPending` LONGTEXT NULL,
    `referrals` LONGTEXT NULL,
    `nextShiftPriorities` LONGTEXT NULL,
    `handedOverById` INTEGER NULL,
    `handedOverByName` VARCHAR(191) NULL,
    `handedOverBySignatureId` VARCHAR(191) NULL,
    `handedOverAt` DATETIME(3) NULL,
    `takenOverById` INTEGER NULL,
    `takenOverByName` VARCHAR(191) NULL,
    `takenOverBySignatureId` VARCHAR(191) NULL,
    `takenOverAt` DATETIME(3) NULL,
    `status` VARCHAR(191) NOT NULL DEFAULT 'DRAFT',
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,
    `createdBy` VARCHAR(191) NULL,
    `createdById` INTEGER NULL,
    `updatedBy` VARCHAR(191) NULL,
    `updatedById` INTEGER NULL,

    INDEX `IpdHandover_admissionId_chartDate_idx`(`admissionId`, `chartDate`),
    INDEX `IpdHandover_status_idx`(`status`),
    UNIQUE INDEX `IpdHandover_admissionId_chartDate_shift_key`(`admissionId`, `chartDate`, `shift`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `OtIntraOpNursingChart` (
    `id` VARCHAR(191) NOT NULL,
    `scheduleId` VARCHAR(191) NOT NULL,
    `wheelInAt` DATETIME(3) NULL,
    `wheelOutAt` DATETIME(3) NULL,
    `modeOfTransfer` VARCHAR(191) NULL,
    `anaesthesia` VARCHAR(191) NULL,
    `position` VARCHAR(191) NULL,
    `positionNotes` TEXT NULL,
    `pressureProtections` TEXT NULL,
    `warmerPlaced` VARCHAR(191) NULL,
    `dvtPumpApplied` VARCHAR(191) NULL,
    `electricCautery` VARCHAR(191) NULL,
    `cauteryPadLocation` VARCHAR(191) NULL,
    `tourniquet` LONGTEXT NULL,
    `catheters` LONGTEXT NULL,
    `instrumentsCount` LONGTEXT NULL,
    `swabRoMopInitial` INTEGER NULL,
    `swabRoMopAdditional` INTEGER NULL,
    `swabRoMopFinal` INTEGER NULL,
    `swabRoGauzeInitial` INTEGER NULL,
    `swabRoGauzeAdditional` INTEGER NULL,
    `swabRoGauzeFinal` INTEGER NULL,
    `swabPlainGauzeInitial` INTEGER NULL,
    `swabPlainGauzeAdditional` INTEGER NULL,
    `swabPlainGauzeFinal` INTEGER NULL,
    `swabThroatPackInitial` INTEGER NULL,
    `swabThroatPackAdditional` INTEGER NULL,
    `swabThroatPackFinal` INTEGER NULL,
    `swabPattiesInitial` INTEGER NULL,
    `swabPattiesAdditional` INTEGER NULL,
    `swabPattiesFinal` INTEGER NULL,
    `swabPeanutsInitial` INTEGER NULL,
    `swabPeanutsAdditional` INTEGER NULL,
    `swabPeanutsFinal` INTEGER NULL,
    `swabRibbonPacksInitial` INTEGER NULL,
    `swabRibbonPacksAdditional` INTEGER NULL,
    `swabRibbonPacksFinal` INTEGER NULL,
    `swabsCountTallied` BOOLEAN NOT NULL DEFAULT false,
    `specimensCulture` TEXT NULL,
    `specimensHistopathology` TEXT NULL,
    `specimensOther` TEXT NULL,
    `specimenHandedOverBy` VARCHAR(191) NULL,
    `specimenHandedOverAt` DATETIME(3) NULL,
    `specimenReceivedBy` VARCHAR(191) NULL,
    `specimenReceivedAt` DATETIME(3) NULL,
    `conditionAtEnd` VARCHAR(191) NULL,
    `dressingType` VARCHAR(191) NULL,
    `dressingNotes` TEXT NULL,
    `patientShiftedTo` VARCHAR(191) NULL,
    `patientShiftedToOther` VARCHAR(191) NULL,
    `scrubNurseName` VARCHAR(191) NULL,
    `scrubNurseId` INTEGER NULL,
    `scrubNurseSignatureId` VARCHAR(191) NULL,
    `scrubNurseSignedAt` DATETIME(3) NULL,
    `floorNurseName` VARCHAR(191) NULL,
    `floorNurseId` INTEGER NULL,
    `floorNurseSignatureId` VARCHAR(191) NULL,
    `floorNurseSignedAt` DATETIME(3) NULL,
    `otInchargeName` VARCHAR(191) NULL,
    `otInchargeId` INTEGER NULL,
    `otInchargeSignatureId` VARCHAR(191) NULL,
    `otInchargeSignedAt` DATETIME(3) NULL,
    `status` VARCHAR(191) NOT NULL DEFAULT 'DRAFT',
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,
    `createdBy` VARCHAR(191) NULL,
    `createdById` INTEGER NULL,
    `updatedBy` VARCHAR(191) NULL,
    `updatedById` INTEGER NULL,

    UNIQUE INDEX `OtIntraOpNursingChart_scheduleId_key`(`scheduleId`),
    INDEX `OtIntraOpNursingChart_status_idx`(`status`),
    INDEX `OtIntraOpNursingChart_wheelInAt_idx`(`wheelInAt`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `IpdHandover` ADD CONSTRAINT `IpdHandover_admissionId_fkey` FOREIGN KEY (`admissionId`) REFERENCES `IpdAdmission`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `OtIntraOpNursingChart` ADD CONSTRAINT `OtIntraOpNursingChart_scheduleId_fkey` FOREIGN KEY (`scheduleId`) REFERENCES `OtSchedule`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;
