-- AlterTable
ALTER TABLE `appointments` ADD COLUMN `BPd` VARCHAR(191) NULL,
    ADD COLUMN `BPs` VARCHAR(191) NULL,
    ADD COLUMN `RR` VARCHAR(191) NULL,
    ADD COLUMN `bloodGroup` VARCHAR(191) NULL,
    ADD COLUMN `height` VARCHAR(191) NULL,
    ADD COLUMN `pulse` VARCHAR(191) NULL,
    ADD COLUMN `spo2` VARCHAR(191) NULL,
    ADD COLUMN `temp` VARCHAR(191) NULL,
    ADD COLUMN `weight` VARCHAR(191) NULL;
