-- CreateTable
CREATE TABLE `IpdInitialAssessment` (
    `id` VARCHAR(191) NOT NULL,
    `admissionId` VARCHAR(191) NOT NULL,
    `department` VARCHAR(191) NULL,
    `admittingConsultant` VARCHAR(191) NULL,
    `allergyNotKnown` BOOLEAN NOT NULL DEFAULT false,
    `allergyDrug` BOOLEAN NOT NULL DEFAULT false,
    `allergyFood` BOOLEAN NOT NULL DEFAULT false,
    `allergyTransfusion` BOOLEAN NOT NULL DEFAULT false,
    `allergyOthers` TEXT NULL,
    `chiefComplaints` LONGTEXT NULL,
    `presentingIllness` LONGTEXT NULL,
    `occupationStatus` VARCHAR(191) NULL,
    `occupationDetails` TEXT NULL,
    `dietType` VARCHAR(191) NULL,
    `bowelBladder` VARCHAR(191) NULL,
    `sleep` VARCHAR(191) NULL,
    `habits` TEXT NULL,
    `hasHypertension` BOOLEAN NOT NULL DEFAULT false,
    `hypertensionSince` VARCHAR(191) NULL,
    `hypertensionMeds` VARCHAR(191) NULL,
    `hasDiabetes` BOOLEAN NOT NULL DEFAULT false,
    `diabetesSince` VARCHAR(191) NULL,
    `diabetesMeds` VARCHAR(191) NULL,
    `hasCardiacDisease` BOOLEAN NOT NULL DEFAULT false,
    `cardiacDiseaseSince` VARCHAR(191) NULL,
    `cardiacDiseaseMeds` VARCHAR(191) NULL,
    `hasWoundDischarge` BOOLEAN NOT NULL DEFAULT false,
    `woundDischargeSince` VARCHAR(191) NULL,
    `hasCopd` BOOLEAN NOT NULL DEFAULT false,
    `copdSince` VARCHAR(191) NULL,
    `hasThyroidDisorder` BOOLEAN NOT NULL DEFAULT false,
    `thyroidDisorderSince` VARCHAR(191) NULL,
    `hasCva` BOOLEAN NOT NULL DEFAULT false,
    `cvaSince` VARCHAR(191) NULL,
    `hasRecurrentInfection` BOOLEAN NOT NULL DEFAULT false,
    `recurrentInfectionSince` VARCHAR(191) NULL,
    `surgicalHistory` LONGTEXT NULL,
    `medicationHistory` LONGTEXT NULL,
    `lmp` VARCHAR(191) NULL,
    `cycleRegular` BOOLEAN NULL,
    `contraception` BOOLEAN NULL,
    `discharge` BOOLEAN NULL,
    `cervicalSmear` BOOLEAN NULL,
    `immunization` VARCHAR(191) NULL,
    `obPain` BOOLEAN NULL,
    `menarche` VARCHAR(191) NULL,
    `menopause` VARCHAR(191) NULL,
    `menorrhagia` BOOLEAN NULL,
    `obstetricHistory` TEXT NULL,
    `familyHistory` LONGTEXT NULL,
    `isGeriatric` BOOLEAN NOT NULL DEFAULT false,
    `mentalStatus` TEXT NULL,
    `emotional` TEXT NULL,
    `communicationsSpeech` TEXT NULL,
    `mobility` TEXT NULL,
    `balance` VARCHAR(191) NULL,
    `bowel` VARCHAR(191) NULL,
    `bladder` VARCHAR(191) NULL,
    `nutrition` TEXT NULL,
    `adl` TEXT NULL,
    `social` VARCHAR(191) NULL,
    `hearing` VARCHAR(191) NULL,
    `vision` VARCHAR(191) NULL,
    `vitalsTemp` VARCHAR(191) NULL,
    `vitalsPulse` VARCHAR(191) NULL,
    `vitalsBP` VARCHAR(191) NULL,
    `vitalsRR` VARCHAR(191) NULL,
    `vitalsWeight` VARCHAR(191) NULL,
    `vitalsHeight` VARCHAR(191) NULL,
    `painScore` INTEGER NULL,
    `painLocation` VARCHAR(191) NULL,
    `painDuration` VARCHAR(191) NULL,
    `examPallor` BOOLEAN NOT NULL DEFAULT false,
    `examEdema` BOOLEAN NOT NULL DEFAULT false,
    `examClubbing` BOOLEAN NOT NULL DEFAULT false,
    `examCyanosis` BOOLEAN NOT NULL DEFAULT false,
    `examIcterus` BOOLEAN NOT NULL DEFAULT false,
    `examEmaciated` BOOLEAN NOT NULL DEFAULT false,
    `examBodyHabitus` VARCHAR(191) NULL,
    `examPsychological` VARCHAR(191) NULL,
    `examLymphNode` TEXT NULL,
    `examOthers` TEXT NULL,
    `cvsNad` BOOLEAN NOT NULL DEFAULT false,
    `cvsFindings` TEXT NULL,
    `entNad` BOOLEAN NOT NULL DEFAULT false,
    `entFindings` TEXT NULL,
    `giNad` BOOLEAN NOT NULL DEFAULT false,
    `giFindings` TEXT NULL,
    `mskNad` BOOLEAN NOT NULL DEFAULT false,
    `mskFindings` TEXT NULL,
    `cnsNad` BOOLEAN NOT NULL DEFAULT false,
    `cnsFindings` TEXT NULL,
    `respNad` BOOLEAN NOT NULL DEFAULT false,
    `respFindings` TEXT NULL,
    `guNad` BOOLEAN NOT NULL DEFAULT false,
    `guFindings` TEXT NULL,
    `hemNad` BOOLEAN NOT NULL DEFAULT false,
    `hemFindings` TEXT NULL,
    `findings` LONGTEXT NULL,
    `provisionalDiagnosis` LONGTEXT NULL,
    `investigationsAdvised` LONGTEXT NULL,
    `problems` LONGTEXT NULL,
    `treatmentPlan` LONGTEXT NULL,
    `otherSystems` LONGTEXT NULL,
    `needsSocialSupport` BOOLEAN NOT NULL DEFAULT false,
    `needsHomeEquipment` BOOLEAN NOT NULL DEFAULT false,
    `needsPhysiotherapy` BOOLEAN NOT NULL DEFAULT false,
    `needsWoundCare` BOOLEAN NOT NULL DEFAULT false,
    `otherDischargeNeeds` TEXT NULL,
    `filledByName` VARCHAR(191) NULL,
    `filledById` INTEGER NULL,
    `filledBySignatureId` VARCHAR(191) NULL,
    `filledAt` DATETIME(3) NULL,
    `consultantName` VARCHAR(191) NULL,
    `consultantId` INTEGER NULL,
    `consultantSignatureId` VARCHAR(191) NULL,
    `consultantSignedAt` DATETIME(3) NULL,
    `status` VARCHAR(191) NOT NULL DEFAULT 'DRAFT',
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,
    `createdBy` VARCHAR(191) NULL,
    `createdById` INTEGER NULL,
    `updatedBy` VARCHAR(191) NULL,
    `updatedById` INTEGER NULL,

    UNIQUE INDEX `IpdInitialAssessment_admissionId_key`(`admissionId`),
    INDEX `IpdInitialAssessment_status_idx`(`status`),
    INDEX `IpdInitialAssessment_filledAt_idx`(`filledAt`),
    INDEX `IpdInitialAssessment_consultantSignedAt_idx`(`consultantSignedAt`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `IpdInitialAssessment` ADD CONSTRAINT `IpdInitialAssessment_admissionId_fkey` FOREIGN KEY (`admissionId`) REFERENCES `IpdAdmission`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;
