// Phase 9.26 / Phase 1 — NABH/QCI Quality Indicator master catalogue.
//
// 108 indicators across 10 chapters (PSQ / ICO / OT / LAB / RAD / PRE / MRD /
// HR / FMS / OPS). Sourced from NABH_QCI_Healthcare_Quality_Indicators_Master.pdf
// at the repo root. The QualityIndicator DB table mirrors this catalogue so an
// admin can disable a row or edit its benchmark at runtime without code
// changes. Each indicator has a stable `qiCode` (e.g. 'PSQ-001').
//
// Mirrors the pattern used by src/api/incident/rule-catalogue.ts.

export type Chapter = 'PSQ' | 'ICO' | 'OT' | 'LAB' | 'RAD' | 'PRE' | 'MRD' | 'HR' | 'FMS' | 'OPS';
export type IndicatorType = 'Process' | 'Outcome' | 'Process/Outcome' | 'Structure';
export type Direction = 'higher-is-bad' | 'lower-is-bad' | 'target-range';
export type RcaRule =
  | 'always'                  // any breach triggers mandatory RCA
  | 'red-2-consecutive'       // red in 2 successive periods
  | 'critical-only'           // only on critical/sentinel tier
  | 'serious-only'            // serious / patient-impacting event
  | 'outbreak-or-red-trend'   // infection-control trend rule
  | 'conditional'             // narrative: e.g. only if medico-legal risk
  | 'never';

export interface QiDef {
  qiCode: string;
  chapter: Chapter;
  nabhRef: string;
  department: string;
  name: string;
  indicatorType: IndicatorType;
  numeratorDef: string;
  denominatorDef: string;
  multiplier: 'NA' | '100' | '1000';
  unit: string;
  frequency: string;
  direction: Direction;
  defaultBenchmark: number | null;  // null = "Hospital defined" in spec
  isCritical: boolean;
  criticalRule?: string;
  dataCaptureFields?: string;
  escalationOwner: string;
  rcaRequiredRule: RcaRule;
  nabhClause?: string;
  sourceUrl?: string;
}

// ─── Source URLs (referenced by indicators) ───────────────────────────────
const URL_KPI =
  'https://nabh-portal-live.s3.ap-south-1.amazonaws.com/wp-content/uploads/2025/07/30130900/NABH-KPI-1.xlsx';
const URL_PSQ_TEMPLATE =
  'https://nabh-portal-live.s3.ap-south-1.amazonaws.com/wp-content/uploads/2025/07/18075929/D.-E-Mitra_FORMAT-06_Template-for-PSQ-Indicators-1.pdf';
const URL_SHCO =
  'https://nabh-portal-live.s3.ap-south-1.amazonaws.com/wp-content/uploads/2025/07/13110738/SHCO-Standards-3rd-Edition.pdf';
const URL_NABH_6E =
  'https://portal.nabh.co/images/Standards/NABH%20Hospital%20Accreditation%20Standard%206th%20Edition%20January%202025.pdf';

// Common capture field bundles (from spec pages 28-36).
const F_TIMESTAMP = 'Timestamp fields, patient ID, location, responsible staff';
const F_INCIDENT = 'Incident ID, patient ID, date/time, severity, location, reporter, action taken';
const F_SURVEILLANCE = 'Surveillance register, device days, procedure counts, audit checklist';
const F_PROCEDURE = 'Procedure logs, anaesthesia records, OT schedule, complication register';
const F_ORDER = 'Order ID, sample/study ID, timestamps, reason codes, communication logs';
const F_SURVEY = 'Survey/complaint/medical record audit fields; patient ID where applicable';
const F_MRD = 'MRD audit checklist, record ID, deficiency type, closure date';
const F_HR_FMS = 'Employee/equipment/incident ID, due date, completion date, status';
const F_OPS = 'Ticket/order/bill ID, timestamp, department, reason, closure status';

// ─── Catalogue (108 indicators, in spec order) ────────────────────────────

export const QI_CATALOGUE: QiDef[] = [
  // ── Patient Safety & Quality (PSQ 3a / Hospital QI) ─────────────────────
  {
    qiCode: 'PSQ-001', chapter: 'PSQ', nabhRef: 'PSQ 3a', department: 'IPD / Medical Ops',
    name: 'Time taken for initial assessment of indoor patients', indicatorType: 'Process',
    numeratorDef: 'Sum of minutes from patient arrival at ward bed to initial assessment completed/documented',
    denominatorDef: 'Total number of IP admissions',
    multiplier: 'NA', unit: 'Minutes', frequency: 'Monthly / Daily dashboard',
    direction: 'higher-is-bad', defaultBenchmark: 30, isCritical: false,
    criticalRule: 'Any high-risk admission delayed beyond max limit',
    dataCaptureFields: 'Admission ID, bed arrival time, assessment completion time, doctor ID',
    escalationOwner: 'Medical Superintendent / Nursing Head', rcaRequiredRule: 'red-2-consecutive',
    nabhClause: 'AAC.4', sourceUrl: URL_KPI,
  },
  {
    qiCode: 'PSQ-002', chapter: 'PSQ', nabhRef: 'PSQ 3a', department: 'Laboratory',
    name: 'Number of reporting errors per 1000 investigations - Lab', indicatorType: 'Outcome',
    numeratorDef: 'Number of lab reporting errors/amended reports attributable to reporting error',
    denominatorDef: 'Total lab investigations/tests performed',
    multiplier: '1000', unit: 'Errors / 1000 tests', frequency: 'Monthly',
    direction: 'higher-is-bad', defaultBenchmark: 0.2, isCritical: true,
    criticalRule: 'Wrong patient / wrong critical value reporting',
    dataCaptureFields: 'Test ID, report ID, amendment flag, error type, verifier, corrected timestamp',
    escalationOwner: 'Lab Head / Quality Manager', rcaRequiredRule: 'critical-only',
    nabhClause: 'COP.10', sourceUrl: URL_KPI,
  },
  {
    qiCode: 'PSQ-003', chapter: 'PSQ', nabhRef: 'PSQ 3a', department: 'Radiology',
    name: 'Number of reporting errors per 1000 investigations - Radiology', indicatorType: 'Outcome',
    numeratorDef: 'Number of radiology reporting errors/amended reports attributable to reporting error',
    denominatorDef: 'Total radiology investigations performed',
    multiplier: '1000', unit: 'Errors / 1000 studies', frequency: 'Monthly',
    direction: 'higher-is-bad', defaultBenchmark: 0.2, isCritical: true,
    criticalRule: 'Wrong patient / wrong site report',
    dataCaptureFields: 'Study ID, modality, report amendment reason, radiologist, verifier',
    escalationOwner: 'Radiology Head / Quality Manager', rcaRequiredRule: 'critical-only',
    nabhClause: 'COP.11', sourceUrl: URL_KPI,
  },
  {
    qiCode: 'PSQ-004', chapter: 'PSQ', nabhRef: 'PSQ 3a', department: 'Diagnostics',
    name: 'Percentage adherence to safety precautions by employees in diagnostics', indicatorType: 'Process',
    numeratorDef: 'Number of audited employees adhering to required safety precautions',
    denominatorDef: 'Total number of employees audited',
    multiplier: '100', unit: '%', frequency: 'Monthly',
    direction: 'lower-is-bad', defaultBenchmark: 95, isCritical: false,
    dataCaptureFields: 'Audit date, employee/role, PPE checklist, compliance status',
    escalationOwner: 'Diagnostics Head / Quality Manager', rcaRequiredRule: 'conditional',
    sourceUrl: URL_KPI,
  },
  {
    qiCode: 'PSQ-005', chapter: 'PSQ', nabhRef: 'PSQ / Hospital QI', department: 'Emergency',
    name: 'Time taken for initial assessment of emergency patients', indicatorType: 'Process',
    numeratorDef: 'Sum of minutes from registration/arrival to initial medical assessment',
    denominatorDef: 'Total emergency patients',
    multiplier: 'NA', unit: 'Minutes', frequency: 'Monthly / Daily dashboard',
    direction: 'higher-is-bad', defaultBenchmark: null, isCritical: false,
    dataCaptureFields: F_TIMESTAMP, escalationOwner: 'Emergency Head', rcaRequiredRule: 'red-2-consecutive',
    sourceUrl: URL_PSQ_TEMPLATE,
  },
  {
    qiCode: 'PSQ-006', chapter: 'PSQ', nabhRef: 'PSQ / Hospital QI', department: 'OPD',
    name: 'Average OPD waiting time for consultation', indicatorType: 'Process',
    numeratorDef: 'Sum of minutes from registration to consultation start',
    denominatorDef: 'Total OPD consultations',
    multiplier: 'NA', unit: 'Minutes', frequency: 'Monthly / Daily dashboard',
    direction: 'higher-is-bad', defaultBenchmark: null, isCritical: false,
    dataCaptureFields: F_TIMESTAMP, escalationOwner: 'OPD Manager', rcaRequiredRule: 'red-2-consecutive',
    sourceUrl: URL_PSQ_TEMPLATE,
  },
  {
    qiCode: 'PSQ-007', chapter: 'PSQ', nabhRef: 'PSQ / Hospital QI', department: 'OPD',
    name: 'Average waiting time for registration', indicatorType: 'Process',
    numeratorDef: 'Sum of minutes from token generation/arrival to registration completion',
    denominatorDef: 'Total patients registered',
    multiplier: 'NA', unit: 'Minutes', frequency: 'Monthly / Daily dashboard',
    direction: 'higher-is-bad', defaultBenchmark: null, isCritical: false,
    dataCaptureFields: F_TIMESTAMP, escalationOwner: 'Front Office Manager', rcaRequiredRule: 'red-2-consecutive',
    sourceUrl: URL_PSQ_TEMPLATE,
  },
  {
    qiCode: 'PSQ-008', chapter: 'PSQ', nabhRef: 'PSQ / Hospital QI', department: 'OPD',
    name: 'Average waiting time for billing', indicatorType: 'Process',
    numeratorDef: 'Sum of minutes from billing queue entry to bill completion',
    denominatorDef: 'Total bills generated',
    multiplier: 'NA', unit: 'Minutes', frequency: 'Monthly / Daily dashboard',
    direction: 'higher-is-bad', defaultBenchmark: null, isCritical: false,
    dataCaptureFields: F_TIMESTAMP, escalationOwner: 'Billing Head', rcaRequiredRule: 'red-2-consecutive',
    sourceUrl: URL_PSQ_TEMPLATE,
  },
  {
    qiCode: 'PSQ-009', chapter: 'PSQ', nabhRef: 'PSQ / Hospital QI', department: 'IPD',
    name: 'Average admission TAT', indicatorType: 'Process',
    numeratorDef: 'Sum of minutes from admission request to bed allotment/arrival',
    denominatorDef: 'Total admissions',
    multiplier: 'NA', unit: 'Minutes', frequency: 'Monthly / Daily dashboard',
    direction: 'higher-is-bad', defaultBenchmark: null, isCritical: false,
    dataCaptureFields: F_TIMESTAMP, escalationOwner: 'Admission Desk Head', rcaRequiredRule: 'red-2-consecutive',
    sourceUrl: URL_PSQ_TEMPLATE,
  },
  {
    qiCode: 'PSQ-010', chapter: 'PSQ', nabhRef: 'PSQ / Hospital QI', department: 'Discharge',
    name: 'Discharge summary completion within defined TAT', indicatorType: 'Process',
    numeratorDef: 'Discharge summaries completed within target TAT',
    denominatorDef: 'Total discharges',
    multiplier: '100', unit: '%', frequency: 'Monthly / Daily dashboard',
    direction: 'lower-is-bad', defaultBenchmark: 95, isCritical: false,
    dataCaptureFields: F_TIMESTAMP, escalationOwner: 'MRD / Medical Ops', rcaRequiredRule: 'red-2-consecutive',
    nabhClause: 'MRD.3', sourceUrl: URL_PSQ_TEMPLATE,
  },
  {
    qiCode: 'PSQ-011', chapter: 'PSQ', nabhRef: 'PSQ / Hospital QI', department: 'Discharge',
    name: 'Average discharge TAT', indicatorType: 'Process',
    numeratorDef: 'Sum of minutes from discharge order to patient exit/bill clearance',
    denominatorDef: 'Total discharges',
    multiplier: 'NA', unit: 'Minutes', frequency: 'Monthly / Daily dashboard',
    direction: 'higher-is-bad', defaultBenchmark: null, isCritical: false,
    dataCaptureFields: F_TIMESTAMP, escalationOwner: 'Operations Head', rcaRequiredRule: 'red-2-consecutive',
    sourceUrl: URL_PSQ_TEMPLATE,
  },
  {
    qiCode: 'PSQ-012', chapter: 'PSQ', nabhRef: 'PSQ / Hospital QI', department: 'Emergency',
    name: 'Door-to-triage time', indicatorType: 'Process',
    numeratorDef: 'Sum of minutes from ED arrival to triage completion',
    denominatorDef: 'Total ED patients',
    multiplier: 'NA', unit: 'Minutes', frequency: 'Monthly / Daily dashboard',
    direction: 'higher-is-bad', defaultBenchmark: null, isCritical: false,
    dataCaptureFields: F_TIMESTAMP, escalationOwner: 'Emergency Head', rcaRequiredRule: 'red-2-consecutive',
    sourceUrl: URL_PSQ_TEMPLATE,
  },
  {
    qiCode: 'PSQ-013', chapter: 'PSQ', nabhRef: 'PSQ / Hospital QI', department: 'Emergency',
    name: 'Door-to-doctor time', indicatorType: 'Process',
    numeratorDef: 'Sum of minutes from ED arrival to doctor assessment',
    denominatorDef: 'Total ED patients',
    multiplier: 'NA', unit: 'Minutes', frequency: 'Monthly / Daily dashboard',
    direction: 'higher-is-bad', defaultBenchmark: null, isCritical: false,
    dataCaptureFields: F_TIMESTAMP, escalationOwner: 'Emergency Head', rcaRequiredRule: 'red-2-consecutive',
    sourceUrl: URL_PSQ_TEMPLATE,
  },
  {
    qiCode: 'PSQ-014', chapter: 'PSQ', nabhRef: 'PSQ / Hospital QI', department: 'Emergency',
    name: 'Code Blue response time compliance', indicatorType: 'Process',
    numeratorDef: 'Number of Code Blue calls attended within target time',
    denominatorDef: 'Total Code Blue calls',
    multiplier: '100', unit: '%', frequency: 'Monthly / Daily dashboard',
    direction: 'lower-is-bad', defaultBenchmark: null, isCritical: false,
    dataCaptureFields: F_TIMESTAMP, escalationOwner: 'Code Blue Committee', rcaRequiredRule: 'red-2-consecutive',
    sourceUrl: URL_PSQ_TEMPLATE,
  },
  {
    qiCode: 'PSQ-015', chapter: 'PSQ', nabhRef: 'PSQ / Hospital QI', department: 'Critical Care',
    name: 'ICU admission TAT after decision', indicatorType: 'Process',
    numeratorDef: 'Sum of minutes from ICU admission decision to ICU bed occupancy',
    denominatorDef: 'Total ICU admissions',
    multiplier: 'NA', unit: 'Minutes', frequency: 'Monthly / Daily dashboard',
    direction: 'higher-is-bad', defaultBenchmark: null, isCritical: false,
    dataCaptureFields: F_TIMESTAMP, escalationOwner: 'ICU Head', rcaRequiredRule: 'red-2-consecutive',
    sourceUrl: URL_PSQ_TEMPLATE,
  },
  {
    qiCode: 'PSQ-016', chapter: 'PSQ', nabhRef: 'PSQ / Hospital QI', department: 'IPD / Nursing',
    name: 'Medication error rate', indicatorType: 'Outcome',
    numeratorDef: 'Number of medication errors reported',
    denominatorDef: 'Total medication administration events',
    multiplier: '100', unit: '%', frequency: 'Monthly / Event-based',
    direction: 'higher-is-bad', defaultBenchmark: null, isCritical: true,
    criticalRule: 'Medication error with patient harm',
    dataCaptureFields: F_INCIDENT, escalationOwner: 'Nursing Head / Pharmacy Head', rcaRequiredRule: 'serious-only',
    sourceUrl: URL_SHCO,
  },
  {
    qiCode: 'PSQ-017', chapter: 'PSQ', nabhRef: 'PSQ / Hospital QI', department: 'Pharmacy',
    name: 'Prescription error rate', indicatorType: 'Outcome',
    numeratorDef: 'Number of prescription errors identified',
    denominatorDef: 'Total prescriptions audited',
    multiplier: '100', unit: '%', frequency: 'Monthly / Event-based',
    direction: 'higher-is-bad', defaultBenchmark: null, isCritical: true,
    criticalRule: 'Prescription error reaching patient with harm',
    dataCaptureFields: F_INCIDENT, escalationOwner: 'Pharmacy Head', rcaRequiredRule: 'serious-only',
    sourceUrl: URL_SHCO,
  },
  {
    qiCode: 'PSQ-018', chapter: 'PSQ', nabhRef: 'PSQ / Hospital QI', department: 'Pharmacy',
    name: 'Dispensing error rate', indicatorType: 'Outcome',
    numeratorDef: 'Number of dispensing errors reported',
    denominatorDef: 'Total items/medications dispensed',
    multiplier: '100', unit: '%', frequency: 'Monthly / Event-based',
    direction: 'higher-is-bad', defaultBenchmark: null, isCritical: true,
    criticalRule: 'Dispensing error with patient harm',
    dataCaptureFields: F_INCIDENT, escalationOwner: 'Pharmacy Head', rcaRequiredRule: 'serious-only',
    sourceUrl: URL_SHCO,
  },
  {
    qiCode: 'PSQ-019', chapter: 'PSQ', nabhRef: 'PSQ / Hospital QI', department: 'Nursing',
    name: 'Administration error rate', indicatorType: 'Outcome',
    numeratorDef: 'Number of medication administration errors',
    denominatorDef: 'Total medication administrations',
    multiplier: '100', unit: '%', frequency: 'Monthly / Event-based',
    direction: 'higher-is-bad', defaultBenchmark: null, isCritical: true,
    criticalRule: 'Administration error with patient harm',
    dataCaptureFields: F_INCIDENT, escalationOwner: 'Nursing Head', rcaRequiredRule: 'serious-only',
    sourceUrl: URL_SHCO,
  },
  {
    qiCode: 'PSQ-020', chapter: 'PSQ', nabhRef: 'PSQ / Hospital QI', department: 'Pharmacy',
    name: 'Near miss medication error rate', indicatorType: 'Outcome',
    numeratorDef: 'Number of medication near misses',
    denominatorDef: 'Total medication orders reviewed',
    multiplier: '100', unit: '%', frequency: 'Monthly / Event-based',
    direction: 'higher-is-bad', defaultBenchmark: null, isCritical: false,
    dataCaptureFields: F_INCIDENT, escalationOwner: 'Pharmacy Head', rcaRequiredRule: 'serious-only',
    sourceUrl: URL_SHCO,
  },
  {
    qiCode: 'PSQ-021', chapter: 'PSQ', nabhRef: 'PSQ / Hospital QI', department: 'Pharmacy',
    name: 'Adverse drug reaction rate', indicatorType: 'Outcome',
    numeratorDef: 'Number of ADR cases reported',
    denominatorDef: 'Total admitted patients or total medication-exposed patients',
    multiplier: '100', unit: '%', frequency: 'Monthly / Event-based',
    direction: 'higher-is-bad', defaultBenchmark: null, isCritical: false,
    dataCaptureFields: F_INCIDENT, escalationOwner: 'Pharmacy & Therapeutics Committee', rcaRequiredRule: 'serious-only',
    sourceUrl: URL_SHCO,
  },
  {
    qiCode: 'PSQ-022', chapter: 'PSQ', nabhRef: 'PSQ / Hospital QI', department: 'Pharmacy',
    name: 'High-alert medication incident rate', indicatorType: 'Outcome',
    numeratorDef: 'Number of high-alert medication incidents',
    denominatorDef: 'Total high-alert medication orders/admin',
    multiplier: '100', unit: '%', frequency: 'Monthly / Event-based',
    direction: 'higher-is-bad', defaultBenchmark: null, isCritical: true,
    criticalRule: 'High-alert medication error reaching patient',
    dataCaptureFields: F_INCIDENT, escalationOwner: 'Pharmacy Head', rcaRequiredRule: 'serious-only',
    sourceUrl: URL_SHCO,
  },
  {
    qiCode: 'PSQ-023', chapter: 'PSQ', nabhRef: 'PSQ / Hospital QI', department: 'Blood Bank',
    name: 'Blood transfusion reaction rate', indicatorType: 'Outcome',
    numeratorDef: 'Number of transfusion reactions',
    denominatorDef: 'Total blood/component transfusions',
    multiplier: '100', unit: '%', frequency: 'Monthly / Event-based',
    direction: 'higher-is-bad', defaultBenchmark: null, isCritical: true,
    criticalRule: 'Major transfusion reaction (haemolytic / anaphylactic / death)',
    dataCaptureFields: F_INCIDENT, escalationOwner: 'Blood Bank Officer', rcaRequiredRule: 'serious-only',
    sourceUrl: URL_SHCO,
  },
  {
    qiCode: 'PSQ-024', chapter: 'PSQ', nabhRef: 'PSQ / Hospital QI', department: 'Nursing',
    name: 'Patient fall rate', indicatorType: 'Outcome',
    numeratorDef: 'Number of patient falls',
    denominatorDef: 'Total patient days',
    multiplier: '1000', unit: 'Falls / 1000 patient days', frequency: 'Monthly / Event-based',
    direction: 'higher-is-bad', defaultBenchmark: null, isCritical: false,
    dataCaptureFields: F_INCIDENT, escalationOwner: 'Nursing Head', rcaRequiredRule: 'serious-only',
    sourceUrl: URL_SHCO,
  },
  {
    qiCode: 'PSQ-025', chapter: 'PSQ', nabhRef: 'PSQ / Hospital QI', department: 'Nursing',
    name: 'Fall with injury rate', indicatorType: 'Outcome',
    numeratorDef: 'Number of falls with injury',
    denominatorDef: 'Total patient days',
    multiplier: '1000', unit: 'Falls with injury / 1000 patient days', frequency: 'Monthly / Event-based',
    direction: 'higher-is-bad', defaultBenchmark: null, isCritical: true,
    criticalRule: 'Fall causing fracture / head injury / death',
    dataCaptureFields: F_INCIDENT, escalationOwner: 'Nursing Head', rcaRequiredRule: 'serious-only',
    sourceUrl: URL_SHCO,
  },
  {
    qiCode: 'PSQ-026', chapter: 'PSQ', nabhRef: 'PSQ / Hospital QI', department: 'Nursing',
    name: 'Pressure ulcer incidence rate', indicatorType: 'Outcome',
    numeratorDef: 'Number of new hospital-acquired pressure ulcers',
    denominatorDef: 'Total at-risk admitted patients or total patient days',
    multiplier: '100', unit: '%', frequency: 'Monthly / Event-based',
    direction: 'higher-is-bad', defaultBenchmark: null, isCritical: true,
    criticalRule: 'Stage 3 / 4 hospital-acquired pressure ulcer',
    dataCaptureFields: F_INCIDENT, escalationOwner: 'Nursing Head', rcaRequiredRule: 'serious-only',
    sourceUrl: URL_SHCO,
  },
  {
    qiCode: 'PSQ-027', chapter: 'PSQ', nabhRef: 'PSQ / Hospital QI', department: 'MRD / Safety',
    name: 'Wrong patient identification incidents', indicatorType: 'Outcome',
    numeratorDef: 'Number of wrong-patient identification incidents',
    denominatorDef: 'Total patient encounters',
    multiplier: '1000', unit: 'Incidents / 1000 encounters', frequency: 'Monthly / Event-based',
    direction: 'higher-is-bad', defaultBenchmark: null, isCritical: true,
    criticalRule: 'Any wrong-patient ID incident — sentinel-class',
    dataCaptureFields: F_INCIDENT, escalationOwner: 'Quality Manager', rcaRequiredRule: 'always',
    sourceUrl: URL_SHCO,
  },
  {
    qiCode: 'PSQ-028', chapter: 'PSQ', nabhRef: 'PSQ / Hospital QI', department: 'Clinical',
    name: 'Adverse clinical events rate', indicatorType: 'Outcome',
    numeratorDef: 'Number of adverse clinical events reported',
    denominatorDef: 'Total admissions',
    multiplier: '100', unit: '%', frequency: 'Monthly / Event-based',
    direction: 'higher-is-bad', defaultBenchmark: null, isCritical: true,
    criticalRule: 'Adverse event causing serious harm or death',
    dataCaptureFields: F_INCIDENT, escalationOwner: 'Quality Manager', rcaRequiredRule: 'serious-only',
    sourceUrl: URL_SHCO,
  },
  {
    qiCode: 'PSQ-029', chapter: 'PSQ', nabhRef: 'PSQ / Hospital QI', department: 'Clinical',
    name: 'Sentinel events count', indicatorType: 'Outcome',
    numeratorDef: 'Number of sentinel events',
    denominatorDef: 'NA',
    multiplier: 'NA', unit: 'Count', frequency: 'Monthly / Event-based',
    direction: 'higher-is-bad', defaultBenchmark: 0, isCritical: true,
    criticalRule: 'Zero-tolerance — any sentinel event is critical',
    dataCaptureFields: F_INCIDENT, escalationOwner: 'Hospital Safety Committee', rcaRequiredRule: 'always',
    sourceUrl: URL_SHCO,
  },
  {
    qiCode: 'PSQ-030', chapter: 'PSQ', nabhRef: 'PSQ / Hospital QI', department: 'OT',
    name: 'Wrong site/procedure/person surgery incidents', indicatorType: 'Outcome',
    numeratorDef: 'Number of wrong site/procedure/person incidents',
    denominatorDef: 'Total surgeries',
    multiplier: '100', unit: '%', frequency: 'Monthly / Event-based',
    direction: 'higher-is-bad', defaultBenchmark: 0, isCritical: true,
    criticalRule: 'Any wrong site / procedure / person — sentinel',
    dataCaptureFields: F_INCIDENT, escalationOwner: 'OT Committee', rcaRequiredRule: 'always',
    sourceUrl: URL_SHCO,
  },

  // ── Infection Control (ICO) ─────────────────────────────────────────────
  {
    qiCode: 'ICO-001', chapter: 'ICO', nabhRef: 'PSQ / Infection Control QI', department: 'Infection Control',
    name: 'Hospital acquired infection rate', indicatorType: 'Process/Outcome',
    numeratorDef: 'Number of HAI cases', denominatorDef: 'Total patient days',
    multiplier: '1000', unit: 'HAI / 1000 patient days', frequency: 'Monthly',
    direction: 'higher-is-bad', defaultBenchmark: null, isCritical: false,
    dataCaptureFields: F_SURVEILLANCE, escalationOwner: 'Infection Control Officer',
    rcaRequiredRule: 'outbreak-or-red-trend', sourceUrl: URL_SHCO,
  },
  {
    qiCode: 'ICO-002', chapter: 'ICO', nabhRef: 'PSQ / Infection Control QI', department: 'Infection Control',
    name: 'Surgical site infection rate', indicatorType: 'Process/Outcome',
    numeratorDef: 'Number of SSI cases', denominatorDef: 'Total surgical procedures',
    multiplier: '100', unit: '%', frequency: 'Monthly',
    direction: 'higher-is-bad', defaultBenchmark: null, isCritical: false,
    dataCaptureFields: F_SURVEILLANCE, escalationOwner: 'Infection Control Officer / OT Head',
    rcaRequiredRule: 'outbreak-or-red-trend', sourceUrl: URL_SHCO,
  },
  {
    qiCode: 'ICO-003', chapter: 'ICO', nabhRef: 'PSQ / Infection Control QI', department: 'ICU',
    name: 'Ventilator associated pneumonia rate', indicatorType: 'Process/Outcome',
    numeratorDef: 'Number of VAP cases', denominatorDef: 'Total ventilator days',
    multiplier: '1000', unit: 'VAP / 1000 ventilator days', frequency: 'Monthly',
    direction: 'higher-is-bad', defaultBenchmark: null, isCritical: false,
    dataCaptureFields: F_SURVEILLANCE, escalationOwner: 'ICU Head / Infection Control Officer',
    rcaRequiredRule: 'outbreak-or-red-trend', sourceUrl: URL_SHCO,
  },
  {
    qiCode: 'ICO-004', chapter: 'ICO', nabhRef: 'PSQ / Infection Control QI', department: 'ICU / Wards',
    name: 'Catheter associated urinary tract infection rate', indicatorType: 'Process/Outcome',
    numeratorDef: 'Number of CAUTI cases', denominatorDef: 'Total urinary catheter days',
    multiplier: '1000', unit: 'CAUTI / 1000 catheter days', frequency: 'Monthly',
    direction: 'higher-is-bad', defaultBenchmark: null, isCritical: false,
    dataCaptureFields: F_SURVEILLANCE, escalationOwner: 'Infection Control Officer',
    rcaRequiredRule: 'outbreak-or-red-trend', sourceUrl: URL_SHCO,
  },
  {
    qiCode: 'ICO-005', chapter: 'ICO', nabhRef: 'PSQ / Infection Control QI', department: 'ICU',
    name: 'Central line associated bloodstream infection rate', indicatorType: 'Process/Outcome',
    numeratorDef: 'Number of CLABSI cases', denominatorDef: 'Total central line days',
    multiplier: '1000', unit: 'CLABSI / 1000 central line days', frequency: 'Monthly',
    direction: 'higher-is-bad', defaultBenchmark: null, isCritical: false,
    dataCaptureFields: F_SURVEILLANCE, escalationOwner: 'Infection Control Officer',
    rcaRequiredRule: 'outbreak-or-red-trend', sourceUrl: URL_SHCO,
  },
  {
    qiCode: 'ICO-006', chapter: 'ICO', nabhRef: 'PSQ / Infection Control QI', department: 'Infection Control',
    name: 'Hand hygiene compliance', indicatorType: 'Process/Outcome',
    numeratorDef: 'Number of hand hygiene opportunities complied',
    denominatorDef: 'Total hand hygiene opportunities observed',
    multiplier: '100', unit: '%', frequency: 'Monthly',
    direction: 'lower-is-bad', defaultBenchmark: 85, isCritical: false,
    dataCaptureFields: F_SURVEILLANCE, escalationOwner: 'Infection Control Nurse',
    rcaRequiredRule: 'outbreak-or-red-trend', sourceUrl: URL_SHCO,
  },
  {
    qiCode: 'ICO-007', chapter: 'ICO', nabhRef: 'PSQ / Infection Control QI', department: 'Infection Control',
    name: 'Biomedical waste segregation compliance', indicatorType: 'Process/Outcome',
    numeratorDef: 'Number of correct BMW segregation observations',
    denominatorDef: 'Total BMW segregation observations',
    multiplier: '100', unit: '%', frequency: 'Monthly',
    direction: 'lower-is-bad', defaultBenchmark: 95, isCritical: false,
    dataCaptureFields: F_SURVEILLANCE, escalationOwner: 'BMW Committee',
    rcaRequiredRule: 'outbreak-or-red-trend', sourceUrl: URL_SHCO,
  },
  {
    qiCode: 'ICO-008', chapter: 'ICO', nabhRef: 'PSQ / Infection Control QI', department: 'CSSD',
    name: 'Sterilization failure rate', indicatorType: 'Process/Outcome',
    numeratorDef: 'Number of failed sterilization cycles/indicators',
    denominatorDef: 'Total sterilization cycles',
    multiplier: '100', unit: '%', frequency: 'Monthly',
    direction: 'higher-is-bad', defaultBenchmark: null, isCritical: true,
    criticalRule: 'Sterilization failure reaching patient',
    dataCaptureFields: F_SURVEILLANCE, escalationOwner: 'CSSD Head',
    rcaRequiredRule: 'outbreak-or-red-trend', sourceUrl: URL_SHCO,
  },
  {
    qiCode: 'ICO-009', chapter: 'ICO', nabhRef: 'PSQ / Infection Control QI', department: 'CSSD',
    name: 'CSSD TAT compliance', indicatorType: 'Process/Outcome',
    numeratorDef: 'Number of sterile packs supplied within target TAT',
    denominatorDef: 'Total sterile pack requests',
    multiplier: '100', unit: '%', frequency: 'Monthly',
    direction: 'lower-is-bad', defaultBenchmark: null, isCritical: false,
    dataCaptureFields: F_SURVEILLANCE, escalationOwner: 'CSSD Head',
    rcaRequiredRule: 'outbreak-or-red-trend', sourceUrl: URL_SHCO,
  },
  {
    qiCode: 'ICO-010', chapter: 'ICO', nabhRef: 'PSQ / Infection Control QI', department: 'Housekeeping',
    name: 'Housekeeping audit compliance', indicatorType: 'Process/Outcome',
    numeratorDef: 'Compliant housekeeping audit checkpoints',
    denominatorDef: 'Total housekeeping audit checkpoints',
    multiplier: '100', unit: '%', frequency: 'Monthly',
    direction: 'lower-is-bad', defaultBenchmark: null, isCritical: false,
    dataCaptureFields: F_SURVEILLANCE, escalationOwner: 'Facility Manager',
    rcaRequiredRule: 'outbreak-or-red-trend', sourceUrl: URL_SHCO,
  },
  {
    qiCode: 'ICO-011', chapter: 'ICO', nabhRef: 'PSQ / Infection Control QI', department: 'Laundry',
    name: 'Linen infection-control compliance', indicatorType: 'Process/Outcome',
    numeratorDef: 'Compliant linen handling observations',
    denominatorDef: 'Total linen handling observations',
    multiplier: '100', unit: '%', frequency: 'Monthly',
    direction: 'lower-is-bad', defaultBenchmark: null, isCritical: false,
    dataCaptureFields: F_SURVEILLANCE, escalationOwner: 'Housekeeping/Laundry Head',
    rcaRequiredRule: 'outbreak-or-red-trend', sourceUrl: URL_SHCO,
  },
  {
    qiCode: 'ICO-012', chapter: 'ICO', nabhRef: 'PSQ / Infection Control QI', department: 'Dietary',
    name: 'Food safety audit compliance', indicatorType: 'Process/Outcome',
    numeratorDef: 'Compliant food safety audit checkpoints',
    denominatorDef: 'Total food safety audit checkpoints',
    multiplier: '100', unit: '%', frequency: 'Monthly',
    direction: 'lower-is-bad', defaultBenchmark: null, isCritical: false,
    dataCaptureFields: F_SURVEILLANCE, escalationOwner: 'Dietary Manager',
    rcaRequiredRule: 'outbreak-or-red-trend', sourceUrl: URL_SHCO,
  },

  // ── Operation Theatre (OT) ──────────────────────────────────────────────
  {
    qiCode: 'OT-001', chapter: 'OT', nabhRef: 'NABH Clinical QI', department: 'OT',
    name: 'OT cancellation rate', indicatorType: 'Process/Outcome',
    numeratorDef: 'Number of scheduled surgeries cancelled', denominatorDef: 'Total scheduled surgeries',
    multiplier: '100', unit: '%', frequency: 'Monthly',
    direction: 'higher-is-bad', defaultBenchmark: null, isCritical: false,
    dataCaptureFields: F_PROCEDURE, escalationOwner: 'OT Manager', rcaRequiredRule: 'serious-only',
    sourceUrl: URL_SHCO,
  },
  {
    qiCode: 'OT-002', chapter: 'OT', nabhRef: 'NABH Clinical QI', department: 'OT',
    name: 'Unplanned return to OT within defined period', indicatorType: 'Process/Outcome',
    numeratorDef: 'Number of unplanned returns to OT', denominatorDef: 'Total surgeries',
    multiplier: '100', unit: '%', frequency: 'Monthly',
    direction: 'higher-is-bad', defaultBenchmark: null, isCritical: true,
    criticalRule: 'Unplanned return due to serious complication',
    dataCaptureFields: F_PROCEDURE, escalationOwner: 'Surgical Head', rcaRequiredRule: 'serious-only',
    sourceUrl: URL_SHCO,
  },
  {
    qiCode: 'OT-003', chapter: 'OT', nabhRef: 'NABH Clinical QI', department: 'OT',
    name: 'Surgical safety checklist compliance', indicatorType: 'Process/Outcome',
    numeratorDef: 'Number of surgeries with fully completed checklist', denominatorDef: 'Total surgeries',
    multiplier: '100', unit: '%', frequency: 'Monthly',
    direction: 'lower-is-bad', defaultBenchmark: 95, isCritical: false,
    dataCaptureFields: F_PROCEDURE, escalationOwner: 'OT Manager', rcaRequiredRule: 'serious-only',
    sourceUrl: URL_SHCO,
  },
  {
    qiCode: 'OT-004', chapter: 'OT', nabhRef: 'NABH Clinical QI', department: 'OT',
    name: 'Pre-anaesthesia check-up completion', indicatorType: 'Process/Outcome',
    numeratorDef: 'Number of surgical patients with completed PAC',
    denominatorDef: 'Total planned surgeries requiring PAC',
    multiplier: '100', unit: '%', frequency: 'Monthly',
    direction: 'lower-is-bad', defaultBenchmark: 95, isCritical: false,
    dataCaptureFields: F_PROCEDURE, escalationOwner: 'Anaesthesia Head', rcaRequiredRule: 'serious-only',
    sourceUrl: URL_SHCO,
  },
  {
    qiCode: 'OT-005', chapter: 'OT', nabhRef: 'NABH Clinical QI', department: 'Anaesthesia',
    name: 'Adverse anaesthesia event rate', indicatorType: 'Process/Outcome',
    numeratorDef: 'Number of adverse anaesthesia events', denominatorDef: 'Total anaesthesia cases',
    multiplier: '100', unit: '%', frequency: 'Monthly',
    direction: 'higher-is-bad', defaultBenchmark: null, isCritical: true,
    criticalRule: 'Adverse anaesthesia event with patient harm',
    dataCaptureFields: F_PROCEDURE, escalationOwner: 'Anaesthesia Head', rcaRequiredRule: 'serious-only',
    sourceUrl: URL_SHCO,
  },
  {
    qiCode: 'OT-006', chapter: 'OT', nabhRef: 'NABH Clinical QI', department: 'Anaesthesia',
    name: 'Anaesthesia-related mortality rate', indicatorType: 'Process/Outcome',
    numeratorDef: 'Number of anaesthesia-related deaths', denominatorDef: 'Total anaesthesia cases',
    multiplier: '100', unit: '%', frequency: 'Monthly',
    direction: 'higher-is-bad', defaultBenchmark: 0, isCritical: true,
    criticalRule: 'Any anaesthesia-related death — zero tolerance',
    dataCaptureFields: F_PROCEDURE, escalationOwner: 'Anaesthesia Head', rcaRequiredRule: 'always',
    sourceUrl: URL_SHCO,
  },
  {
    qiCode: 'OT-007', chapter: 'OT', nabhRef: 'NABH Clinical QI', department: 'OT',
    name: 'Post-operative complication rate', indicatorType: 'Process/Outcome',
    numeratorDef: 'Number of post-op complications within defined period', denominatorDef: 'Total surgeries',
    multiplier: '100', unit: '%', frequency: 'Monthly',
    direction: 'higher-is-bad', defaultBenchmark: null, isCritical: false,
    dataCaptureFields: F_PROCEDURE, escalationOwner: 'Surgical Head', rcaRequiredRule: 'serious-only',
    sourceUrl: URL_SHCO,
  },
  {
    qiCode: 'OT-008', chapter: 'OT', nabhRef: 'NABH Clinical QI', department: 'OT',
    name: 'OT utilization rate', indicatorType: 'Process/Outcome',
    numeratorDef: 'Total utilized OT hours', denominatorDef: 'Total available OT hours',
    multiplier: '100', unit: '%', frequency: 'Monthly',
    direction: 'target-range', defaultBenchmark: 75, isCritical: false,
    dataCaptureFields: F_PROCEDURE, escalationOwner: 'OT Manager', rcaRequiredRule: 'serious-only',
    sourceUrl: URL_SHCO,
  },
  {
    qiCode: 'OT-009', chapter: 'OT', nabhRef: 'NABH Clinical QI', department: 'OT',
    name: 'First case start time compliance', indicatorType: 'Process/Outcome',
    numeratorDef: 'Number of first OT cases started on time', denominatorDef: 'Total first OT cases',
    multiplier: '100', unit: '%', frequency: 'Monthly',
    direction: 'lower-is-bad', defaultBenchmark: null, isCritical: false,
    dataCaptureFields: F_PROCEDURE, escalationOwner: 'OT Manager', rcaRequiredRule: 'serious-only',
    sourceUrl: URL_SHCO,
  },
  {
    qiCode: 'OT-010', chapter: 'OT', nabhRef: 'NABH Clinical QI', department: 'OT',
    name: 'Surgical specimen labelling error rate', indicatorType: 'Process/Outcome',
    numeratorDef: 'Number of specimen labelling errors', denominatorDef: 'Total surgical specimens sent',
    multiplier: '100', unit: '%', frequency: 'Monthly',
    direction: 'higher-is-bad', defaultBenchmark: 0, isCritical: true,
    criticalRule: 'Specimen mislabelled — patient-impacting',
    dataCaptureFields: F_PROCEDURE, escalationOwner: 'OT / Lab Head', rcaRequiredRule: 'serious-only',
    sourceUrl: URL_SHCO,
  },
  {
    qiCode: 'OT-011', chapter: 'OT', nabhRef: 'NABH Clinical QI', department: 'ICU',
    name: 'ICU mortality rate', indicatorType: 'Process/Outcome',
    numeratorDef: 'Number of ICU deaths', denominatorDef: 'Total ICU admissions',
    multiplier: '100', unit: '%', frequency: 'Monthly',
    direction: 'higher-is-bad', defaultBenchmark: null, isCritical: false,
    dataCaptureFields: F_PROCEDURE, escalationOwner: 'ICU Head', rcaRequiredRule: 'serious-only',
    sourceUrl: URL_SHCO,
  },
  {
    qiCode: 'OT-012', chapter: 'OT', nabhRef: 'NABH Clinical QI', department: 'ICU',
    name: 'Unplanned ICU transfer/readmission rate', indicatorType: 'Process/Outcome',
    numeratorDef: 'Number of unplanned ICU transfers/readmissions',
    denominatorDef: 'Total ward discharges/transfers as applicable',
    multiplier: '100', unit: '%', frequency: 'Monthly',
    direction: 'higher-is-bad', defaultBenchmark: null, isCritical: false,
    dataCaptureFields: F_PROCEDURE, escalationOwner: 'ICU Head', rcaRequiredRule: 'serious-only',
    sourceUrl: URL_SHCO,
  },

  // ── Laboratory (LAB) ────────────────────────────────────────────────────
  {
    qiCode: 'LAB-001', chapter: 'LAB', nabhRef: 'Diagnostics QI', department: 'Laboratory',
    name: 'Lab sample rejection rate', indicatorType: 'Process/Outcome',
    numeratorDef: 'Number of rejected samples', denominatorDef: 'Total samples received',
    multiplier: '100', unit: '%', frequency: 'Monthly',
    direction: 'higher-is-bad', defaultBenchmark: null, isCritical: false,
    dataCaptureFields: F_ORDER, escalationOwner: 'Lab Head', rcaRequiredRule: 'serious-only',
    sourceUrl: URL_KPI,
  },
  {
    qiCode: 'LAB-002', chapter: 'LAB', nabhRef: 'Diagnostics QI', department: 'Laboratory',
    name: 'Critical value reporting TAT compliance', indicatorType: 'Process/Outcome',
    numeratorDef: 'Number of critical values communicated within target time',
    denominatorDef: 'Total critical values identified',
    multiplier: '100', unit: '%', frequency: 'Monthly',
    direction: 'lower-is-bad', defaultBenchmark: 100, isCritical: true,
    criticalRule: 'Critical lab value not communicated',
    dataCaptureFields: F_ORDER, escalationOwner: 'Lab Head', rcaRequiredRule: 'serious-only',
    nabhClause: 'COP.10', sourceUrl: URL_KPI,
  },
  {
    qiCode: 'LAB-003', chapter: 'LAB', nabhRef: 'Diagnostics QI', department: 'Laboratory',
    name: 'Lab report TAT compliance', indicatorType: 'Process/Outcome',
    numeratorDef: 'Number of lab reports released within defined TAT',
    denominatorDef: 'Total lab reports',
    multiplier: '100', unit: '%', frequency: 'Monthly',
    direction: 'lower-is-bad', defaultBenchmark: null, isCritical: false,
    dataCaptureFields: F_ORDER, escalationOwner: 'Lab Head', rcaRequiredRule: 'serious-only',
    sourceUrl: URL_KPI,
  },
  {
    qiCode: 'LAB-004', chapter: 'LAB', nabhRef: 'Diagnostics QI', department: 'Laboratory',
    name: 'Panic value documentation compliance', indicatorType: 'Process/Outcome',
    numeratorDef: 'Number of panic/critical values with documented communication',
    denominatorDef: 'Total panic/critical values',
    multiplier: '100', unit: '%', frequency: 'Monthly',
    direction: 'lower-is-bad', defaultBenchmark: 100, isCritical: true,
    criticalRule: 'Panic value without documented communication',
    dataCaptureFields: F_ORDER, escalationOwner: 'Lab Head', rcaRequiredRule: 'serious-only',
    sourceUrl: URL_KPI,
  },
  {
    qiCode: 'LAB-005', chapter: 'LAB', nabhRef: 'Diagnostics QI', department: 'Laboratory',
    name: 'Internal quality control failure rate', indicatorType: 'Process/Outcome',
    numeratorDef: 'Number of IQC failures', denominatorDef: 'Total IQC runs',
    multiplier: '100', unit: '%', frequency: 'Monthly',
    direction: 'higher-is-bad', defaultBenchmark: null, isCritical: false,
    dataCaptureFields: F_ORDER, escalationOwner: 'Lab Quality Manager', rcaRequiredRule: 'serious-only',
    sourceUrl: URL_KPI,
  },
  {
    qiCode: 'LAB-006', chapter: 'LAB', nabhRef: 'Diagnostics QI', department: 'Laboratory',
    name: 'External quality assurance participation compliance', indicatorType: 'Process/Outcome',
    numeratorDef: 'Number of applicable tests covered by EQAS/PT', denominatorDef: 'Total applicable tests',
    multiplier: '100', unit: '%', frequency: 'Monthly',
    direction: 'lower-is-bad', defaultBenchmark: 100, isCritical: false,
    dataCaptureFields: F_ORDER, escalationOwner: 'Lab Quality Manager', rcaRequiredRule: 'serious-only',
    sourceUrl: URL_KPI,
  },

  // ── Radiology (RAD) ─────────────────────────────────────────────────────
  {
    qiCode: 'RAD-001', chapter: 'RAD', nabhRef: 'Diagnostics QI', department: 'Radiology',
    name: 'Radiology report TAT compliance', indicatorType: 'Process/Outcome',
    numeratorDef: 'Number of reports released within defined TAT', denominatorDef: 'Total radiology reports',
    multiplier: '100', unit: '%', frequency: 'Monthly',
    direction: 'lower-is-bad', defaultBenchmark: null, isCritical: false,
    dataCaptureFields: F_ORDER, escalationOwner: 'Radiology Head', rcaRequiredRule: 'serious-only',
    sourceUrl: URL_KPI,
  },
  {
    qiCode: 'RAD-002', chapter: 'RAD', nabhRef: 'Diagnostics QI', department: 'Radiology',
    name: 'Critical radiology finding communication compliance', indicatorType: 'Process/Outcome',
    numeratorDef: 'Critical findings communicated and documented within target time',
    denominatorDef: 'Total critical radiology findings',
    multiplier: '100', unit: '%', frequency: 'Monthly',
    direction: 'lower-is-bad', defaultBenchmark: 100, isCritical: true,
    criticalRule: 'Critical radiology finding not communicated',
    dataCaptureFields: F_ORDER, escalationOwner: 'Radiology Head', rcaRequiredRule: 'serious-only',
    sourceUrl: URL_KPI,
  },
  {
    qiCode: 'RAD-003', chapter: 'RAD', nabhRef: 'Diagnostics QI', department: 'Radiology',
    name: 'Repeat imaging rate due to technical error', indicatorType: 'Process/Outcome',
    numeratorDef: 'Number of repeat imaging studies due to technical error', denominatorDef: 'Total imaging studies',
    multiplier: '100', unit: '%', frequency: 'Monthly',
    direction: 'higher-is-bad', defaultBenchmark: null, isCritical: false,
    dataCaptureFields: F_ORDER, escalationOwner: 'Radiology Head', rcaRequiredRule: 'serious-only',
    sourceUrl: URL_KPI,
  },
  {
    qiCode: 'RAD-004', chapter: 'RAD', nabhRef: 'Diagnostics QI', department: 'Radiology',
    name: 'Radiation safety audit compliance', indicatorType: 'Process/Outcome',
    numeratorDef: 'Compliant radiation safety checkpoints', denominatorDef: 'Total radiation safety checkpoints audited',
    multiplier: '100', unit: '%', frequency: 'Monthly',
    direction: 'lower-is-bad', defaultBenchmark: null, isCritical: false,
    dataCaptureFields: F_ORDER, escalationOwner: 'Radiology Safety Officer', rcaRequiredRule: 'serious-only',
    sourceUrl: URL_KPI,
  },

  // ── Patient Rights & Education (PRE) ────────────────────────────────────
  {
    qiCode: 'PRE-001', chapter: 'PRE', nabhRef: 'PRE / Patient Rights QI', department: 'PRE',
    name: 'Patient satisfaction score - OPD', indicatorType: 'Process/Outcome',
    numeratorDef: 'Sum of OPD satisfaction scores or satisfied responses',
    denominatorDef: 'Total OPD survey responses',
    multiplier: '100', unit: '% / Score', frequency: 'Monthly',
    direction: 'lower-is-bad', defaultBenchmark: 80, isCritical: false,
    dataCaptureFields: F_SURVEY, escalationOwner: 'Patient Experience Manager', rcaRequiredRule: 'serious-only',
    sourceUrl: URL_NABH_6E,
  },
  {
    qiCode: 'PRE-002', chapter: 'PRE', nabhRef: 'PRE / Patient Rights QI', department: 'PRE',
    name: 'Patient satisfaction score - IPD', indicatorType: 'Process/Outcome',
    numeratorDef: 'Sum of IPD satisfaction scores or satisfied responses',
    denominatorDef: 'Total IPD survey responses',
    multiplier: '100', unit: '% / Score', frequency: 'Monthly',
    direction: 'lower-is-bad', defaultBenchmark: 80, isCritical: false,
    dataCaptureFields: F_SURVEY, escalationOwner: 'Patient Experience Manager', rcaRequiredRule: 'serious-only',
    sourceUrl: URL_NABH_6E,
  },
  {
    qiCode: 'PRE-003', chapter: 'PRE', nabhRef: 'PRE / Patient Rights QI', department: 'PRE',
    name: 'Complaint rate', indicatorType: 'Process/Outcome',
    numeratorDef: 'Number of complaints received', denominatorDef: 'Total OPD/IPD footfall or encounters',
    multiplier: '1000', unit: 'Complaints / 1000 encounters', frequency: 'Monthly',
    direction: 'higher-is-bad', defaultBenchmark: null, isCritical: false,
    dataCaptureFields: F_SURVEY, escalationOwner: 'Grievance Officer', rcaRequiredRule: 'serious-only',
    sourceUrl: URL_NABH_6E,
  },
  {
    qiCode: 'PRE-004', chapter: 'PRE', nabhRef: 'PRE / Patient Rights QI', department: 'PRE',
    name: 'Complaint closure within TAT', indicatorType: 'Process/Outcome',
    numeratorDef: 'Number of complaints closed within defined TAT', denominatorDef: 'Total complaints closed/received',
    multiplier: '100', unit: '%', frequency: 'Monthly',
    direction: 'lower-is-bad', defaultBenchmark: 90, isCritical: false,
    dataCaptureFields: F_SURVEY, escalationOwner: 'Grievance Officer', rcaRequiredRule: 'serious-only',
    sourceUrl: URL_NABH_6E,
  },
  {
    qiCode: 'PRE-005', chapter: 'PRE', nabhRef: 'PRE / Patient Rights QI', department: 'PRE',
    name: 'Informed consent compliance', indicatorType: 'Process/Outcome',
    numeratorDef: 'Number of applicable cases with complete valid consent',
    denominatorDef: 'Total applicable cases audited',
    multiplier: '100', unit: '%', frequency: 'Monthly',
    direction: 'lower-is-bad', defaultBenchmark: 100, isCritical: false,
    dataCaptureFields: F_SURVEY, escalationOwner: 'Quality Manager', rcaRequiredRule: 'serious-only',
    sourceUrl: URL_NABH_6E,
  },
  {
    qiCode: 'PRE-006', chapter: 'PRE', nabhRef: 'PRE / Patient Rights QI', department: 'PRE',
    name: 'Patient identification band compliance', indicatorType: 'Process/Outcome',
    numeratorDef: 'Number of audited inpatients with correct ID band', denominatorDef: 'Total inpatients audited',
    multiplier: '100', unit: '%', frequency: 'Monthly',
    direction: 'lower-is-bad', defaultBenchmark: 100, isCritical: false,
    dataCaptureFields: F_SURVEY, escalationOwner: 'Nursing Head', rcaRequiredRule: 'serious-only',
    sourceUrl: URL_NABH_6E,
  },
  {
    qiCode: 'PRE-007', chapter: 'PRE', nabhRef: 'PRE / Patient Rights QI', department: 'PRE',
    name: 'Patient education documentation compliance', indicatorType: 'Process/Outcome',
    numeratorDef: 'Number of records with documented patient/family education',
    denominatorDef: 'Total records audited',
    multiplier: '100', unit: '%', frequency: 'Monthly',
    direction: 'lower-is-bad', defaultBenchmark: null, isCritical: false,
    dataCaptureFields: F_SURVEY, escalationOwner: 'Nursing Head', rcaRequiredRule: 'serious-only',
    sourceUrl: URL_NABH_6E,
  },
  {
    qiCode: 'PRE-008', chapter: 'PRE', nabhRef: 'PRE / Patient Rights QI', department: 'PRE',
    name: 'Discharge counselling documentation compliance', indicatorType: 'Process/Outcome',
    numeratorDef: 'Number of discharges with documented counselling', denominatorDef: 'Total discharges audited',
    multiplier: '100', unit: '%', frequency: 'Monthly',
    direction: 'lower-is-bad', defaultBenchmark: null, isCritical: false,
    dataCaptureFields: F_SURVEY, escalationOwner: 'Nursing Head', rcaRequiredRule: 'serious-only',
    sourceUrl: URL_NABH_6E,
  },
  {
    qiCode: 'PRE-009', chapter: 'PRE', nabhRef: 'PRE / Patient Rights QI', department: 'PRE',
    name: 'Consent form deficiency rate', indicatorType: 'Process/Outcome',
    numeratorDef: 'Number of consent forms with deficiencies', denominatorDef: 'Total consent forms audited',
    multiplier: '100', unit: '%', frequency: 'Monthly',
    direction: 'higher-is-bad', defaultBenchmark: null, isCritical: false,
    dataCaptureFields: F_SURVEY, escalationOwner: 'MRD Head', rcaRequiredRule: 'serious-only',
    sourceUrl: URL_NABH_6E,
  },
  {
    qiCode: 'PRE-010', chapter: 'PRE', nabhRef: 'PRE / Patient Rights QI', department: 'PRE',
    name: 'Patient privacy breach incidents', indicatorType: 'Process/Outcome',
    numeratorDef: 'Number of privacy/confidentiality breach incidents', denominatorDef: 'Total patient encounters',
    multiplier: '1000', unit: 'Incidents / 1000 encounters', frequency: 'Monthly',
    direction: 'higher-is-bad', defaultBenchmark: 0, isCritical: true,
    criticalRule: 'Any privacy / confidentiality breach',
    dataCaptureFields: F_SURVEY, escalationOwner: 'Quality Manager', rcaRequiredRule: 'serious-only',
    sourceUrl: URL_NABH_6E,
  },

  // ── Medical Records (MRD) ───────────────────────────────────────────────
  {
    qiCode: 'MRD-001', chapter: 'MRD', nabhRef: 'MRD / PSQ QI', department: 'MRD',
    name: 'Incomplete medical record rate', indicatorType: 'Process',
    numeratorDef: 'Number of incomplete records', denominatorDef: 'Total records audited',
    multiplier: '100', unit: '%', frequency: 'Monthly',
    direction: 'higher-is-bad', defaultBenchmark: null, isCritical: false,
    dataCaptureFields: F_MRD, escalationOwner: 'MRD Head', rcaRequiredRule: 'conditional',
    nabhClause: 'MRD.1', sourceUrl: URL_NABH_6E,
  },
  {
    qiCode: 'MRD-002', chapter: 'MRD', nabhRef: 'MRD / PSQ QI', department: 'MRD',
    name: 'Medical record availability TAT compliance', indicatorType: 'Process',
    numeratorDef: 'Number of records made available within target time', denominatorDef: 'Total records requested',
    multiplier: '100', unit: '%', frequency: 'Monthly',
    direction: 'lower-is-bad', defaultBenchmark: null, isCritical: false,
    dataCaptureFields: F_MRD, escalationOwner: 'MRD Head', rcaRequiredRule: 'conditional',
    sourceUrl: URL_NABH_6E,
  },
  {
    qiCode: 'MRD-003', chapter: 'MRD', nabhRef: 'MRD / PSQ QI', department: 'MRD',
    name: 'Coding error rate', indicatorType: 'Process',
    numeratorDef: 'Number of coding errors found', denominatorDef: 'Total coded records audited',
    multiplier: '100', unit: '%', frequency: 'Monthly',
    direction: 'higher-is-bad', defaultBenchmark: null, isCritical: false,
    dataCaptureFields: F_MRD, escalationOwner: 'MRD Head', rcaRequiredRule: 'conditional',
    sourceUrl: URL_NABH_6E,
  },
  {
    qiCode: 'MRD-004', chapter: 'MRD', nabhRef: 'MRD / PSQ QI', department: 'MRD',
    name: 'Death summary completion TAT compliance', indicatorType: 'Process',
    numeratorDef: 'Death summaries completed within target TAT', denominatorDef: 'Total deaths',
    multiplier: '100', unit: '%', frequency: 'Monthly',
    direction: 'lower-is-bad', defaultBenchmark: null, isCritical: false,
    dataCaptureFields: F_MRD, escalationOwner: 'MRD / Medical Ops', rcaRequiredRule: 'conditional',
    sourceUrl: URL_NABH_6E,
  },
  {
    qiCode: 'MRD-005', chapter: 'MRD', nabhRef: 'MRD / PSQ QI', department: 'MRD',
    name: 'Death audit completion compliance', indicatorType: 'Process',
    numeratorDef: 'Deaths audited within defined timeframe', denominatorDef: 'Total deaths requiring audit',
    multiplier: '100', unit: '%', frequency: 'Monthly',
    direction: 'lower-is-bad', defaultBenchmark: null, isCritical: false,
    dataCaptureFields: F_MRD, escalationOwner: 'Mortality Committee', rcaRequiredRule: 'conditional',
    sourceUrl: URL_NABH_6E,
  },
  {
    qiCode: 'MRD-006', chapter: 'MRD', nabhRef: 'MRD / PSQ QI', department: 'MRD',
    name: 'Documentation error rate', indicatorType: 'Process',
    numeratorDef: 'Number of documentation deficiencies/errors', denominatorDef: 'Total records audited',
    multiplier: '100', unit: '%', frequency: 'Monthly',
    direction: 'higher-is-bad', defaultBenchmark: null, isCritical: false,
    dataCaptureFields: F_MRD, escalationOwner: 'MRD Head', rcaRequiredRule: 'conditional',
    sourceUrl: URL_NABH_6E,
  },
  {
    qiCode: 'MRD-007', chapter: 'MRD', nabhRef: 'MRD / PSQ QI', department: 'MRD',
    name: 'Abbreviation misuse rate', indicatorType: 'Process',
    numeratorDef: 'Number of records with non-approved abbreviations', denominatorDef: 'Total records audited',
    multiplier: '100', unit: '%', frequency: 'Monthly',
    direction: 'higher-is-bad', defaultBenchmark: null, isCritical: false,
    dataCaptureFields: F_MRD, escalationOwner: 'MRD Head', rcaRequiredRule: 'conditional',
    sourceUrl: URL_NABH_6E,
  },
  {
    qiCode: 'MRD-008', chapter: 'MRD', nabhRef: 'MRD / PSQ QI', department: 'MRD',
    name: 'High-risk consent documentation compliance', indicatorType: 'Process',
    numeratorDef: 'High-risk cases with complete consent documentation', denominatorDef: 'Total high-risk cases audited',
    multiplier: '100', unit: '%', frequency: 'Monthly',
    direction: 'lower-is-bad', defaultBenchmark: 100, isCritical: false,
    dataCaptureFields: F_MRD, escalationOwner: 'MRD / Quality Manager', rcaRequiredRule: 'conditional',
    sourceUrl: URL_NABH_6E,
  },

  // ── Human Resources (HR) ────────────────────────────────────────────────
  {
    qiCode: 'HR-001', chapter: 'HR', nabhRef: 'NABH Support Services QI', department: 'HR',
    name: 'Mandatory training compliance', indicatorType: 'Process/Outcome',
    numeratorDef: 'Number of staff completed mandatory training', denominatorDef: 'Total eligible staff',
    multiplier: '100', unit: '%', frequency: 'Monthly / Quarterly',
    direction: 'lower-is-bad', defaultBenchmark: 90, isCritical: false,
    dataCaptureFields: F_HR_FMS, escalationOwner: 'HR Head', rcaRequiredRule: 'serious-only',
    sourceUrl: URL_NABH_6E,
  },
  {
    qiCode: 'HR-002', chapter: 'HR', nabhRef: 'NABH Support Services QI', department: 'HR',
    name: 'BLS training compliance', indicatorType: 'Process/Outcome',
    numeratorDef: 'Number of applicable staff with valid BLS training', denominatorDef: 'Total applicable staff',
    multiplier: '100', unit: '%', frequency: 'Monthly / Quarterly',
    direction: 'lower-is-bad', defaultBenchmark: 95, isCritical: false,
    dataCaptureFields: F_HR_FMS, escalationOwner: 'HR / Training Coordinator', rcaRequiredRule: 'serious-only',
    sourceUrl: URL_NABH_6E,
  },
  {
    qiCode: 'HR-003', chapter: 'HR', nabhRef: 'NABH Support Services QI', department: 'HR',
    name: 'Fire safety training compliance', indicatorType: 'Process/Outcome',
    numeratorDef: 'Number of staff trained in fire safety', denominatorDef: 'Total eligible staff',
    multiplier: '100', unit: '%', frequency: 'Monthly / Quarterly',
    direction: 'lower-is-bad', defaultBenchmark: 90, isCritical: false,
    dataCaptureFields: F_HR_FMS, escalationOwner: 'HR / Safety Officer', rcaRequiredRule: 'serious-only',
    sourceUrl: URL_NABH_6E,
  },
  {
    qiCode: 'HR-004', chapter: 'HR', nabhRef: 'NABH Support Services QI', department: 'HR',
    name: 'Credentialing and privileging compliance', indicatorType: 'Process/Outcome',
    numeratorDef: 'Number of doctors with valid credentialing/privileging', denominatorDef: 'Total active doctors',
    multiplier: '100', unit: '%', frequency: 'Monthly / Quarterly',
    direction: 'lower-is-bad', defaultBenchmark: 100, isCritical: false,
    dataCaptureFields: F_HR_FMS, escalationOwner: 'HR / Medical Admin', rcaRequiredRule: 'serious-only',
    sourceUrl: URL_NABH_6E,
  },
  {
    qiCode: 'HR-005', chapter: 'HR', nabhRef: 'NABH Support Services QI', department: 'HR',
    name: 'Staff health check compliance', indicatorType: 'Process/Outcome',
    numeratorDef: 'Number of staff with completed health checks/vaccination as applicable',
    denominatorDef: 'Total eligible staff',
    multiplier: '100', unit: '%', frequency: 'Monthly / Quarterly',
    direction: 'lower-is-bad', defaultBenchmark: 90, isCritical: false,
    dataCaptureFields: F_HR_FMS, escalationOwner: 'HR / Infection Control', rcaRequiredRule: 'serious-only',
    sourceUrl: URL_NABH_6E,
  },
  {
    qiCode: 'HR-006', chapter: 'HR', nabhRef: 'NABH Support Services QI', department: 'HR',
    name: 'Needle stick injury rate among staff', indicatorType: 'Process/Outcome',
    numeratorDef: 'Number of needle stick injuries', denominatorDef: 'Total clinical staff or staff-hours',
    multiplier: '100', unit: '%', frequency: 'Monthly / Quarterly',
    direction: 'higher-is-bad', defaultBenchmark: null, isCritical: true,
    criticalRule: 'Needle stick with high-risk source patient',
    dataCaptureFields: F_HR_FMS, escalationOwner: 'Infection Control Officer', rcaRequiredRule: 'serious-only',
    sourceUrl: URL_NABH_6E,
  },

  // ── Facility Management Services (FMS) ──────────────────────────────────
  {
    qiCode: 'FMS-001', chapter: 'FMS', nabhRef: 'NABH Support Services QI', department: 'Facility',
    name: 'Equipment preventive maintenance compliance', indicatorType: 'Process/Outcome',
    numeratorDef: 'Number of equipment PMs completed on schedule', denominatorDef: 'Total PMs due',
    multiplier: '100', unit: '%', frequency: 'Monthly / Quarterly',
    direction: 'lower-is-bad', defaultBenchmark: 95, isCritical: false,
    dataCaptureFields: F_HR_FMS, escalationOwner: 'Biomedical Head', rcaRequiredRule: 'serious-only',
    sourceUrl: URL_NABH_6E,
  },
  {
    qiCode: 'FMS-002', chapter: 'FMS', nabhRef: 'NABH Support Services QI', department: 'Facility',
    name: 'Equipment calibration compliance', indicatorType: 'Process/Outcome',
    numeratorDef: 'Number of equipment calibrated within due date', denominatorDef: 'Total equipment requiring calibration',
    multiplier: '100', unit: '%', frequency: 'Monthly / Quarterly',
    direction: 'lower-is-bad', defaultBenchmark: 95, isCritical: false,
    dataCaptureFields: F_HR_FMS, escalationOwner: 'Biomedical Head', rcaRequiredRule: 'serious-only',
    sourceUrl: URL_NABH_6E,
  },
  {
    qiCode: 'FMS-003', chapter: 'FMS', nabhRef: 'NABH Support Services QI', department: 'Facility',
    name: 'Critical equipment breakdown rate', indicatorType: 'Process/Outcome',
    numeratorDef: 'Number of critical equipment breakdowns', denominatorDef: 'Total critical equipment',
    multiplier: '100', unit: '%', frequency: 'Monthly / Quarterly',
    direction: 'higher-is-bad', defaultBenchmark: null, isCritical: true,
    criticalRule: 'Critical equipment failure impacting patient care',
    dataCaptureFields: F_HR_FMS, escalationOwner: 'Biomedical Head', rcaRequiredRule: 'serious-only',
    sourceUrl: URL_NABH_6E,
  },
  {
    qiCode: 'FMS-004', chapter: 'FMS', nabhRef: 'NABH Support Services QI', department: 'Facility',
    name: 'Utility failure incidents', indicatorType: 'Process/Outcome',
    numeratorDef: 'Number of utility failure incidents', denominatorDef: 'NA',
    multiplier: 'NA', unit: 'Count', frequency: 'Monthly / Quarterly',
    direction: 'higher-is-bad', defaultBenchmark: 0, isCritical: true,
    criticalRule: 'Utility failure (power/water/gas) impacting patient care',
    dataCaptureFields: F_HR_FMS, escalationOwner: 'Facility Manager', rcaRequiredRule: 'serious-only',
    sourceUrl: URL_NABH_6E,
  },
  {
    qiCode: 'FMS-005', chapter: 'FMS', nabhRef: 'NABH Support Services QI', department: 'Facility',
    name: 'Fire drill compliance', indicatorType: 'Process/Outcome',
    numeratorDef: 'Number of fire drills conducted as planned', denominatorDef: 'Number of fire drills planned',
    multiplier: '100', unit: '%', frequency: 'Monthly / Quarterly',
    direction: 'lower-is-bad', defaultBenchmark: 100, isCritical: false,
    dataCaptureFields: F_HR_FMS, escalationOwner: 'Safety Officer', rcaRequiredRule: 'serious-only',
    sourceUrl: URL_NABH_6E,
  },
  {
    qiCode: 'FMS-006', chapter: 'FMS', nabhRef: 'NABH Support Services QI', department: 'Facility',
    name: 'Mock drill compliance', indicatorType: 'Process/Outcome',
    numeratorDef: 'Number of mock drills conducted as planned', denominatorDef: 'Number of mock drills planned',
    multiplier: '100', unit: '%', frequency: 'Monthly / Quarterly',
    direction: 'lower-is-bad', defaultBenchmark: 100, isCritical: false,
    dataCaptureFields: F_HR_FMS, escalationOwner: 'Safety Officer', rcaRequiredRule: 'serious-only',
    sourceUrl: URL_NABH_6E,
  },
  {
    qiCode: 'FMS-007', chapter: 'FMS', nabhRef: 'NABH Support Services QI', department: 'Facility',
    name: 'Security incident rate', indicatorType: 'Process/Outcome',
    numeratorDef: 'Number of security incidents', denominatorDef: 'Total patient/visitor encounters or days',
    multiplier: '1000', unit: 'Incidents / 1000 encounters', frequency: 'Monthly / Quarterly',
    direction: 'higher-is-bad', defaultBenchmark: null, isCritical: false,
    dataCaptureFields: F_HR_FMS, escalationOwner: 'Security Head', rcaRequiredRule: 'serious-only',
    sourceUrl: URL_NABH_6E,
  },
  {
    qiCode: 'FMS-008', chapter: 'FMS', nabhRef: 'NABH Support Services QI', department: 'Facility',
    name: 'Ambulance response time compliance', indicatorType: 'Process/Outcome',
    numeratorDef: 'Number of ambulance calls responded within target time', denominatorDef: 'Total ambulance calls',
    multiplier: '100', unit: '%', frequency: 'Monthly / Quarterly',
    direction: 'lower-is-bad', defaultBenchmark: 90, isCritical: false,
    dataCaptureFields: F_HR_FMS, escalationOwner: 'Ambulance Manager', rcaRequiredRule: 'serious-only',
    sourceUrl: URL_NABH_6E,
  },
  {
    qiCode: 'FMS-009', chapter: 'FMS', nabhRef: 'NABH Support Services QI', department: 'Facility',
    name: 'Maintenance complaint closure within TAT', indicatorType: 'Process/Outcome',
    numeratorDef: 'Maintenance complaints closed within TAT', denominatorDef: 'Total maintenance complaints',
    multiplier: '100', unit: '%', frequency: 'Monthly / Quarterly',
    direction: 'lower-is-bad', defaultBenchmark: 85, isCritical: false,
    dataCaptureFields: F_HR_FMS, escalationOwner: 'Facility Manager', rcaRequiredRule: 'serious-only',
    sourceUrl: URL_NABH_6E,
  },
  {
    qiCode: 'FMS-010', chapter: 'FMS', nabhRef: 'NABH Support Services QI', department: 'Facility',
    name: 'Lift/electrical safety checklist compliance', indicatorType: 'Process/Outcome',
    numeratorDef: 'Compliant checklist observations', denominatorDef: 'Total checklist observations',
    multiplier: '100', unit: '%', frequency: 'Monthly / Quarterly',
    direction: 'lower-is-bad', defaultBenchmark: 95, isCritical: false,
    dataCaptureFields: F_HR_FMS, escalationOwner: 'Facility Manager', rcaRequiredRule: 'serious-only',
    sourceUrl: URL_NABH_6E,
  },

  // ── Operational (OPS) ───────────────────────────────────────────────────
  {
    qiCode: 'OPS-001', chapter: 'OPS', nabhRef: 'Operational QI', department: 'Billing',
    name: 'Billing error rate', indicatorType: 'Process/Outcome',
    numeratorDef: 'Number of billing errors/complaints validated', denominatorDef: 'Total bills generated',
    multiplier: '100', unit: '%', frequency: 'Monthly / Daily dashboard',
    direction: 'higher-is-bad', defaultBenchmark: null, isCritical: false,
    dataCaptureFields: F_OPS, escalationOwner: 'Billing Head', rcaRequiredRule: 'conditional',
    sourceUrl: URL_NABH_6E,
  },
  {
    qiCode: 'OPS-002', chapter: 'OPS', nabhRef: 'Operational QI', department: 'Insurance',
    name: 'Insurance/pre-auth TAT compliance', indicatorType: 'Process/Outcome',
    numeratorDef: 'Number of pre-auths completed within target TAT', denominatorDef: 'Total pre-auth requests',
    multiplier: '100', unit: '%', frequency: 'Monthly / Daily dashboard',
    direction: 'lower-is-bad', defaultBenchmark: null, isCritical: false,
    dataCaptureFields: F_OPS, escalationOwner: 'Insurance Desk Head', rcaRequiredRule: 'conditional',
    sourceUrl: URL_NABH_6E,
  },
  {
    qiCode: 'OPS-003', chapter: 'OPS', nabhRef: 'Operational QI', department: 'Pharmacy',
    name: 'Stock-out incidence for critical drugs', indicatorType: 'Process/Outcome',
    numeratorDef: 'Number of critical drug stock-out events', denominatorDef: 'Total critical drugs monitored or days',
    multiplier: '100', unit: '% / Count', frequency: 'Monthly / Daily dashboard',
    direction: 'higher-is-bad', defaultBenchmark: 0, isCritical: true,
    criticalRule: 'Critical drug stock-out during clinical demand',
    dataCaptureFields: F_OPS, escalationOwner: 'Pharmacy Head', rcaRequiredRule: 'conditional',
    sourceUrl: URL_NABH_6E,
  },
  {
    qiCode: 'OPS-004', chapter: 'OPS', nabhRef: 'Operational QI', department: 'Pharmacy',
    name: 'Expired drug incidence', indicatorType: 'Process/Outcome',
    numeratorDef: 'Number of expired drugs found in audit', denominatorDef: 'Total drug items audited',
    multiplier: '100', unit: '%', frequency: 'Monthly / Daily dashboard',
    direction: 'higher-is-bad', defaultBenchmark: null, isCritical: false,
    dataCaptureFields: F_OPS, escalationOwner: 'Pharmacy Head', rcaRequiredRule: 'conditional',
    sourceUrl: URL_NABH_6E,
  },
  {
    qiCode: 'OPS-005', chapter: 'OPS', nabhRef: 'Operational QI', department: 'Store',
    name: 'Indent fulfilment TAT compliance', indicatorType: 'Process/Outcome',
    numeratorDef: 'Indents fulfilled within target TAT', denominatorDef: 'Total indents',
    multiplier: '100', unit: '%', frequency: 'Monthly / Daily dashboard',
    direction: 'lower-is-bad', defaultBenchmark: null, isCritical: false,
    dataCaptureFields: F_OPS, escalationOwner: 'Stores Head', rcaRequiredRule: 'conditional',
    sourceUrl: URL_NABH_6E,
  },
  {
    qiCode: 'OPS-006', chapter: 'OPS', nabhRef: 'Operational QI', department: 'Housekeeping',
    name: 'Bed turnaround time', indicatorType: 'Process/Outcome',
    numeratorDef: 'Sum of minutes from discharge/transfer to bed ready', denominatorDef: 'Total bed turnovers',
    multiplier: 'NA', unit: 'Minutes', frequency: 'Monthly / Daily dashboard',
    direction: 'higher-is-bad', defaultBenchmark: null, isCritical: false,
    dataCaptureFields: F_OPS, escalationOwner: 'Nursing/Housekeeping Head', rcaRequiredRule: 'conditional',
    sourceUrl: URL_NABH_6E,
  },
  {
    qiCode: 'OPS-007', chapter: 'OPS', nabhRef: 'Operational QI', department: 'Dietary',
    name: 'Diet delivery TAT compliance', indicatorType: 'Process/Outcome',
    numeratorDef: 'Meals delivered within scheduled time', denominatorDef: 'Total meals served',
    multiplier: '100', unit: '%', frequency: 'Monthly / Daily dashboard',
    direction: 'lower-is-bad', defaultBenchmark: null, isCritical: false,
    dataCaptureFields: F_OPS, escalationOwner: 'Dietary Manager', rcaRequiredRule: 'conditional',
    sourceUrl: URL_NABH_6E,
  },
  {
    qiCode: 'OPS-008', chapter: 'OPS', nabhRef: 'Operational QI', department: 'Transport',
    name: 'Patient transport TAT compliance', indicatorType: 'Process/Outcome',
    numeratorDef: 'Transport requests fulfilled within target TAT', denominatorDef: 'Total patient transport requests',
    multiplier: '100', unit: '%', frequency: 'Monthly / Daily dashboard',
    direction: 'lower-is-bad', defaultBenchmark: null, isCritical: false,
    dataCaptureFields: F_OPS, escalationOwner: 'Operations Head', rcaRequiredRule: 'conditional',
    sourceUrl: URL_NABH_6E,
  },
  {
    qiCode: 'OPS-009', chapter: 'OPS', nabhRef: 'Operational QI', department: 'IT',
    name: 'Application downtime', indicatorType: 'Process/Outcome',
    numeratorDef: 'Total downtime minutes for hospital application', denominatorDef: 'Total scheduled operating minutes',
    multiplier: '100', unit: '% downtime', frequency: 'Monthly / Daily dashboard',
    direction: 'higher-is-bad', defaultBenchmark: 1, isCritical: false,
    dataCaptureFields: F_OPS, escalationOwner: 'IT Head', rcaRequiredRule: 'conditional',
    sourceUrl: URL_NABH_6E,
  },
  {
    qiCode: 'OPS-010', chapter: 'OPS', nabhRef: 'Operational QI', department: 'IT',
    name: 'Critical system incident closure within SLA', indicatorType: 'Process/Outcome',
    numeratorDef: 'Critical IT incidents closed within SLA', denominatorDef: 'Total critical IT incidents',
    multiplier: '100', unit: '%', frequency: 'Monthly / Daily dashboard',
    direction: 'lower-is-bad', defaultBenchmark: 95, isCritical: false,
    dataCaptureFields: F_OPS, escalationOwner: 'IT Head', rcaRequiredRule: 'conditional',
    sourceUrl: URL_NABH_6E,
  },
];

export const QI_INDEX: Record<string, QiDef> = QI_CATALOGUE.reduce<Record<string, QiDef>>(
  (acc, def) => { acc[def.qiCode] = def; return acc; },
  {},
);

export function getQiDef(qiCode: string): QiDef | undefined {
  return QI_INDEX[qiCode];
}
