-- AlterTable
ALTER TABLE `IpdPrescription` ADD COLUMN `dispensedAt` DATETIME(3) NULL,
    ADD COLUMN `dispensedBy` VARCHAR(191) NULL,
    ADD COLUMN `dispensedById` INTEGER NULL,
    ADD COLUMN `dispensedQty` INTEGER NULL,
    ADD COLUMN `isStatBypass` BOOLEAN NOT NULL DEFAULT false,
    ADD COLUMN `nurseCollectedAt` DATETIME(3) NULL,
    ADD COLUMN `nurseCollectedBy` VARCHAR(191) NULL,
    ADD COLUMN `nurseCollectedById` INTEGER NULL,
    ADD COLUMN `nurseCollectedQty` INTEGER NULL,
    ADD COLUMN `nurseReturnReason` TEXT NULL,
    ADD COLUMN `nurseReturnedAt` DATETIME(3) NULL,
    ADD COLUMN `nurseReturnedBy` VARCHAR(191) NULL,
    ADD COLUMN `nurseReturnedById` INTEGER NULL,
    ADD COLUMN `pharmacyAckAt` DATETIME(3) NULL,
    ADD COLUMN `pharmacyAckBy` VARCHAR(191) NULL,
    ADD COLUMN `pharmacyAckById` INTEGER NULL,
    ADD COLUMN `pharmacyRejectedAt` DATETIME(3) NULL,
    ADD COLUMN `pharmacyRejectedBy` VARCHAR(191) NULL,
    ADD COLUMN `pharmacyRejectedById` INTEGER NULL,
    ADD COLUMN `pharmacyRejectedReason` TEXT NULL,
    ADD COLUMN `sentToPharmacyAt` DATETIME(3) NULL,
    ADD COLUMN `stockProbeAt` DATETIME(3) NULL,
    ADD COLUMN `stockProbeJson` TEXT NULL,
    ADD COLUMN `substitutedBrand` VARCHAR(191) NULL,
    ADD COLUMN `substitutedReason` TEXT NULL;
