-- CreateTable
CREATE TABLE `StaffHandover` (
    `id` VARCHAR(191) NOT NULL,
    `eventType` VARCHAR(191) NOT NULL,
    `shift` VARCHAR(191) NOT NULL,
    `department` VARCHAR(191) NULL,
    `wardId` VARCHAR(191) NULL,
    `status` VARCHAR(191) NOT NULL DEFAULT 'OPEN',
    `raisedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `originatorName` VARCHAR(191) NOT NULL,
    `originatorRole` VARCHAR(191) NULL,
    `originatorBy` VARCHAR(191) NULL,
    `originatorById` INTEGER NULL,
    `originatorSignatureId` VARCHAR(191) NULL,
    `acknowledgedAt` DATETIME(3) NULL,
    `receiverName` VARCHAR(191) NULL,
    `receiverRole` VARCHAR(191) NULL,
    `receiverBy` VARCHAR(191) NULL,
    `receiverById` INTEGER NULL,
    `receiverSignatureId` VARCHAR(191) NULL,
    `supervisorName` VARCHAR(191) NULL,
    `supervisorBy` VARCHAR(191) NULL,
    `supervisorById` INTEGER NULL,
    `supervisorSignatureId` VARCHAR(191) NULL,
    `rationale` TEXT NOT NULL,
    `patientsAffected` LONGTEXT NULL,
    `pendingTasks` TEXT NULL,
    `declineReason` TEXT NULL,
    `closedAt` DATETIME(3) NULL,
    `closedBy` VARCHAR(191) NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,

    INDEX `StaffHandover_status_idx`(`status`),
    INDEX `StaffHandover_eventType_idx`(`eventType`),
    INDEX `StaffHandover_wardId_idx`(`wardId`),
    INDEX `StaffHandover_raisedAt_idx`(`raisedAt`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
