-- Phase 9.4d — OpProcedure (outpatient minor procedure flow).
-- Strictly additive: one new table.

CREATE TABLE `OpProcedure` (
    `id` VARCHAR(191) NOT NULL,
    `procedureNo` VARCHAR(191) NOT NULL,
    `prn` VARCHAR(191) NOT NULL,
    `patientName` VARCHAR(191) NOT NULL,
    `age` INTEGER NULL,
    `gender` VARCHAR(191) NULL,
    `phoneNumber` VARCHAR(191) NULL,
    `opdAppointmentId` INTEGER NULL,
    `sourceModule` VARCHAR(191) NOT NULL DEFAULT 'opd',
    `procedureName` VARCHAR(191) NOT NULL,
    `procedureCode` VARCHAR(191) NULL,
    `departmentId` INTEGER NULL,
    `departmentName` VARCHAR(191) NULL,
    `performingDoctor` VARCHAR(191) NOT NULL,
    `performingDoctorId` INTEGER NULL,
    `assistantName` VARCHAR(191) NULL,
    `roomName` VARCHAR(191) NULL,
    `anaesthesiaType` VARCHAR(191) NULL,
    `anaesthesiaAgent` VARCHAR(191) NULL,
    `scheduledAt` DATETIME(3) NULL,
    `startedAt` DATETIME(3) NULL,
    `endedAt` DATETIME(3) NULL,
    `preProcedureNotes` TEXT NULL,
    `procedureSteps` LONGTEXT NULL,
    `findings` LONGTEXT NULL,
    `complications` TEXT NULL,
    `conditionAtEnd` VARCHAR(191) NULL,
    `disposition` VARCHAR(191) NULL,
    `postProcedureInstructions` TEXT NULL,
    `signedBy` VARCHAR(191) NULL,
    `signedById` INTEGER NULL,
    `signatureId` VARCHAR(191) NULL,
    `signedAt` DATETIME(3) NULL,
    `status` VARCHAR(191) NOT NULL DEFAULT 'SCHEDULED',
    `cancelReason` TEXT NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,
    `createdBy` VARCHAR(191) NULL,
    `createdById` INTEGER NULL,

    UNIQUE INDEX `OpProcedure_procedureNo_key`(`procedureNo`),
    INDEX `OpProcedure_prn_idx`(`prn`),
    INDEX `OpProcedure_scheduledAt_idx`(`scheduledAt`),
    INDEX `OpProcedure_status_idx`(`status`),
    INDEX `OpProcedure_opdAppointmentId_idx`(`opdAppointmentId`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
