-- AlterTable
ALTER TABLE `ERAssessment` MODIFY `name` LONGTEXT NULL,
    MODIFY `age` LONGTEXT NULL,
    MODIFY `sex` LONGTEXT NULL,
    MODIFY `uhId` LONGTEXT NULL,
    MODIFY `date` LONGTEXT NULL,
    MODIFY `time` LONGTEXT NULL,
    MODIFY `pr` LONGTEXT NULL,
    MODIFY `bp` LONGTEXT NULL,
    MODIFY `rr` LONGTEXT NULL,
    MODIFY `spo2` LONGTEXT NULL,
    MODIFY `temp` LONGTEXT NULL,
    MODIFY `grbs` LONGTEXT NULL,
    MODIFY `mlcNo` LONGTEXT NULL,
    MODIFY `presentingComplaints` LONGTEXT NULL,
    MODIFY `pastHistory` LONGTEXT NULL,
    MODIFY `regularMedications` LONGTEXT NULL,
    MODIFY `abcdeAssessment` LONGTEXT NULL,
    MODIFY `examination` LONGTEXT NULL,
    MODIFY `investigation` LONGTEXT NULL,
    MODIFY `procedureDone` LONGTEXT NULL,
    MODIFY `provisionalDiagnosis` LONGTEXT NULL,
    MODIFY `treatmentAdministered` LONGTEXT NULL,
    MODIFY `referralDepartment` LONGTEXT NULL,
    MODIFY `disposition` LONGTEXT NULL,
    MODIFY `dischargePR` LONGTEXT NULL,
    MODIFY `dischargeBP` LONGTEXT NULL,
    MODIFY `dischargeRR` LONGTEXT NULL,
    MODIFY `dischargeSpo2` LONGTEXT NULL,
    MODIFY `dischargeTemp` LONGTEXT NULL,
    MODIFY `otherInstructions` LONGTEXT NULL,
    MODIFY `doctorSpecialty` LONGTEXT NULL,
    MODIFY `doctorSign` LONGTEXT NULL;

-- AlterTable
ALTER TABLE `OPDAssessment` MODIFY `specify` LONGTEXT NULL,
    MODIFY `allergies` LONGTEXT NULL,
    MODIFY `history` LONGTEXT NULL,
    MODIFY `examination` LONGTEXT NULL,
    MODIFY `investigation` LONGTEXT NULL,
    MODIFY `treatmentPlan` LONGTEXT NULL,
    MODIFY `doctorSealSign` LONGTEXT NULL;
