-- AlterTable
ALTER TABLE `OtSafetyChecklist` ADD COLUMN `bloodAvailabilityChecked` BOOLEAN NOT NULL DEFAULT false,
    ADD COLUMN `correctPatientConfirmed` BOOLEAN NOT NULL DEFAULT false,
    ADD COLUMN `correctSiteConfirmed` BOOLEAN NOT NULL DEFAULT false,
    ADD COLUMN `fastingStatusConfirmed` BOOLEAN NOT NULL DEFAULT false,
    ADD COLUMN `instrumentsAvailable` BOOLEAN NOT NULL DEFAULT false,
    ADD COLUMN `ivLineSecured` BOOLEAN NOT NULL DEFAULT false,
    ADD COLUMN `patientShiftedSafely` BOOLEAN NOT NULL DEFAULT false,
    ADD COLUMN `postOpInstructionsGiven` BOOLEAN NOT NULL DEFAULT false,
    ADD COLUMN `procedureCompletedConfirmed` BOOLEAN NOT NULL DEFAULT false,
    ADD COLUMN `spongeNeedleCountDone` BOOLEAN NOT NULL DEFAULT false,
    ADD COLUMN `sterilityConfirmed` BOOLEAN NOT NULL DEFAULT false;

-- CreateTable
CREATE TABLE `OtWardToOtChecklist` (
    `id` VARCHAR(191) NOT NULL,
    `scheduleId` VARCHAR(191) NOT NULL,
    `status` VARCHAR(191) NOT NULL DEFAULT 'DRAFT',
    `identityBandChecked` BOOLEAN NOT NULL DEFAULT false,
    `surgeryConsentSigned` BOOLEAN NOT NULL DEFAULT false,
    `anaesthesiaConsentSigned` BOOLEAN NOT NULL DEFAULT false,
    `surgicalSiteMarked` BOOLEAN NOT NULL DEFAULT false,
    `preOpAssessmentCompleted` BOOLEAN NOT NULL DEFAULT false,
    `allergyStatusChecked` BOOLEAN NOT NULL DEFAULT false,
    `investigationsAvailable` BOOLEAN NOT NULL DEFAULT false,
    `bloodGroupCrossMatchDone` BOOLEAN NOT NULL DEFAULT false,
    `bloodProductsArranged` BOOLEAN NOT NULL DEFAULT false,
    `vitalSignsRecorded` BOOLEAN NOT NULL DEFAULT false,
    `ivLineSecured` BOOLEAN NOT NULL DEFAULT false,
    `preOpMedicationsGiven` BOOLEAN NOT NULL DEFAULT false,
    `antibioticAdministered` BOOLEAN NOT NULL DEFAULT false,
    `fastingConfirmed` BOOLEAN NOT NULL DEFAULT false,
    `dentureRemoved` BOOLEAN NOT NULL DEFAULT false,
    `jewelleryRemoved` BOOLEAN NOT NULL DEFAULT false,
    `nailPolishMakeupRemoved` BOOLEAN NOT NULL DEFAULT false,
    `contactLensRemoved` BOOLEAN NOT NULL DEFAULT false,
    `prosthesisHearingAidRemoved` BOOLEAN NOT NULL DEFAULT false,
    `urinaryCatheterSecured` BOOLEAN NOT NULL DEFAULT false,
    `skinPreparationCompleted` BOOLEAN NOT NULL DEFAULT false,
    `operativeSiteCleanedShaved` BOOLEAN NOT NULL DEFAULT false,
    `personalBelongingsHandedOver` BOOLEAN NOT NULL DEFAULT false,
    `caseSheetReportsSent` BOOLEAN NOT NULL DEFAULT false,
    `patientShiftedOnTrolleySafely` BOOLEAN NOT NULL DEFAULT false,
    `wardRemarks` TEXT NULL,
    `sideRailsSecured` BOOLEAN NOT NULL DEFAULT false,
    `oxygenSupportProvided` BOOLEAN NOT NULL DEFAULT false,
    `emergencyDrugsEquipmentAccompanied` BOOLEAN NOT NULL DEFAULT false,
    `patientMonitoredDuringTransfer` BOOLEAN NOT NULL DEFAULT false,
    `handoverGivenToOtNurse` BOOLEAN NOT NULL DEFAULT false,
    `transferRemarks` TEXT NULL,
    `otrIdentityReconfirmed` BOOLEAN NOT NULL DEFAULT false,
    `otrSurgerySiteConfirmed` BOOLEAN NOT NULL DEFAULT false,
    `otrConsentVerified` BOOLEAN NOT NULL DEFAULT false,
    `otrAllergyChecked` BOOLEAN NOT NULL DEFAULT false,
    `otrNbmReconfirmed` BOOLEAN NOT NULL DEFAULT false,
    `otrInvestigationsAvailable` BOOLEAN NOT NULL DEFAULT false,
    `otrImplantsBloodConfirmed` BOOLEAN NOT NULL DEFAULT false,
    `otrVitalSignsChecked` BOOLEAN NOT NULL DEFAULT false,
    `otrIvAccessPatent` BOOLEAN NOT NULL DEFAULT false,
    `otrPreOpMedicationsCompleted` BOOLEAN NOT NULL DEFAULT false,
    `otrSurgicalSiteMarkingVisible` BOOLEAN NOT NULL DEFAULT false,
    `otrJewelleryDentureRemoved` BOOLEAN NOT NULL DEFAULT false,
    `otrFoleyCatheterDrainsChecked` BOOLEAN NOT NULL DEFAULT false,
    `otrSkinPreparationAdequate` BOOLEAN NOT NULL DEFAULT false,
    `otrPatientShiftedToOtTableSafely` BOOLEAN NOT NULL DEFAULT false,
    `otReceivingRemarks` TEXT NULL,
    `wardNurseName` VARCHAR(191) NULL,
    `wardNurseSignedAt` DATETIME(3) NULL,
    `wardNurseSignedById` INTEGER NULL,
    `wardNurseSignatureId` VARCHAR(191) NULL,
    `otReceivingNurseName` VARCHAR(191) NULL,
    `otReceivingNurseSignedAt` DATETIME(3) NULL,
    `otReceivingNurseSignedById` INTEGER NULL,
    `otReceivingNurseSignatureId` VARCHAR(191) NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `createdBy` VARCHAR(191) NULL,

    UNIQUE INDEX `OtWardToOtChecklist_scheduleId_key`(`scheduleId`),
    INDEX `OtWardToOtChecklist_scheduleId_idx`(`scheduleId`),
    INDEX `OtWardToOtChecklist_status_idx`(`status`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `OtWardToOtChecklist` ADD CONSTRAINT `OtWardToOtChecklist_scheduleId_fkey` FOREIGN KEY (`scheduleId`) REFERENCES `OtSchedule`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;
